// Copyright (c) 2026 Christian Mayer and the Mundus Mirabilis contributors.
// SPDX-License-Identifier: Apache-2.0

/**
 * The ELO Arena demo: a leaderboard of the shipped rulesets (generated by the
 * Python Monte-Carlo ELO script during CI), a form to enter an arbitrary
 * character that is then ranked live by the WASM engine + the JS ELO formula,
 * and a head-to-head panel that computes fight-win probabilities from ELO
 * ratings (with an optional live Monte-Carlo confirmation).
 *
 * The page is plain ES modules — no build step. At deploy time the CI copies
 * the WASM assets into ./wasm/, the rulesets into ./rulesets/, and writes the
 * leaderboards into ./data/ (all three folders are gitignored here).
 */
import { init } from './rpg-browser.js';
import { expectedScore, ELO_K, ELO_STANDARD, rankNewcomer } from './elo.js';
import {
  COMBAT_STATS, DEFAULT_WEAPON, GAMES_PER_OPPONENT, LIVE_FIGHTS, MAX_ROUNDS,
  RANK_OPPONENTS_PER_ROUND, RANK_ROUNDS, RULESETS, SEED_ADD, SEED_MOD, SEED_MUL,
  SEED_STRIDE,
} from './constants.js';
import { renderFightRound, renderKnownSpells } from './transcript.js';

const $ = (sel) => document.querySelector(sel);
const status = $('#status');
const leaderboardBody = $('#leaderboard-body');
const leaderboardNote = $('#leaderboard-note');

let rpg = null;
let meta = null;
let entriesByName = new Map(); // id -> display name (from the ruleset)
let leaderboard = []; // [{rank,id,name,rating,games,wins,losses,draws,win_pct}]
let you = null; // { name, rating, spec } for the ranked character (spec kept alive)
let selection = []; // ids of the selected rows (max 2)
let duelLive = null; // { winsA, winsB, draws } of the last live run for the current pair
let fightDetail = null; // transcript of the last single detailed fight for the current pair
let formDebounce = 0;
let leaderboardMeta = ''; // metadata line shown under the leaderboard table
let leaderboardInitial = ELO_STANDARD; // the leaderboard's own anchor when known
let rulesetData = null; // parsed copy of the loaded ruleset JSON (for the pickers)
let archetypes = []; // [{id, name, attributes, skills, spells_known}] — the "class" selector
let spells = []; // [{id, name, levelTag, costTag, damageTag, damaging, classes, traditions}]

function setStatus(text, isError = false) {
  status.textContent = text;
  status.classList.toggle('error', isError);
}

/**
 * Renders the loaded ruleset's OWN licence in a box at the bottom of the
 * page. The rules are NOT Apache-2.0 (the engine and this page are), so the
 * box states that distinction up front, then shows the licence statement,
 * where the rights holder states it, the source document, and the verbatim
 * notice/attribution the licence requires (e.g. the ORC Notice).
 */
function renderLicence() {
  const el = $('#ruleset-licence-box');
  el.innerHTML = '';
  if (!meta?.licence) {
    el.hidden = true;
    return;
  }

  const head = document.createElement('div');
  head.className = 'licence-box-head';

  const eyebrow = document.createElement('span');
  eyebrow.className = 'licence-eyebrow';
  eyebrow.textContent = 'Ruleset licence';

  const title = document.createElement('h2');
  title.textContent = 'The ruleset is not Apache-2.0';

  const note = document.createElement('p');
  note.className = 'licence-note';
  note.append('RPG OS — the engine and this page — is Apache-2.0. ');
  const strong = document.createElement('b');
  strong.textContent =
    'The licence below belongs to the loaded ruleset, not to the application:';
  note.append(strong, ' read it before reusing or redistributing the rules.');
  head.append(eyebrow, title, note);

  const body = document.createElement('div');
  body.className = 'licence-box-body';

  const statement = document.createElement('p');
  statement.className = 'licence-statement';
  statement.textContent = meta.licence;
  body.append(statement);

  const metaLine = document.createElement('p');
  metaLine.className = 'licence-meta';
  if (meta.source) {
    const src = document.createElement('span');
    src.textContent = `Source: ${meta.source}`;
    metaLine.append(src);
  }
  if (meta.licence_source) {
    if (metaLine.childNodes.length > 0) metaLine.append(document.createTextNode(' · '));
    const link = document.createElement('a');
    link.href = meta.licence_source;
    link.target = '_blank';
    link.rel = 'noopener noreferrer';
    link.textContent = 'Where the licence is stated';
    metaLine.append(link);
  }
  if (metaLine.childNodes.length > 0) body.append(metaLine);

  let details = null;
  for (const key of ['licence_notice', 'attribution']) {
    if (meta?.[key]) {
      if (!details) {
        details = document.createElement('div');
        details.className = 'licence-details';
      }
      const p = document.createElement('p');
      p.className = 'licence-detail';
      p.textContent = meta[key];
      details.append(p);
    }
  }
  if (details) body.append(details);

  el.append(head, body);
  el.hidden = false;
}

// ---------------------------------------------------------------------------
// init / ruleset loading
// ---------------------------------------------------------------------------

async function initEngine() {
  setStatus('Loading engine…');
  try {
    rpg = await init();
  } catch (err) {
    setStatus(`Engine failed to load: ${err.message}`, true);
    throw err;
  }
  const select = $('#ruleset-select');
  for (const [id, cfg] of Object.entries(RULESETS)) {
    const opt = document.createElement('option');
    opt.value = id;
    opt.textContent = cfg.label;
    select.append(opt);
  }
  select.addEventListener('change', () => loadRuleset(select.value));
  await loadRuleset(select.value);
}

async function loadRuleset(id) {
  const cfg = RULESETS[id];
  setStatus(`Loading ${cfg.label}…`);
  clearForm();
  selection = [];
  $('#ruleset-licence-box').hidden = true;
  you?.spec?.dispose();
  you = null;
  renderDuel();

  try {
    const rulesetJson = await (await fetch(`rulesets/${cfg.file}`)).text();
    rpg.loadRuleset(rulesetJson);
    meta = rpg.meta();
    // The engine is the source of truth for resolution; the pickers (the
    // class selector and the spell list) are built from a parsed copy of the
    // very same JSON the engine just loaded.
    try {
      rulesetData = JSON.parse(rulesetJson);
    } catch {
      rulesetData = null;
    }
    archetypes = (rulesetData?.data?.archetypes ?? []).map(archetypeSummary);
    spells = (rulesetData?.data?.spells ?? []).map(spellSummary);
    renderLicence();
    const entries = rpg.entries();
    entriesByName = new Map(entries.map((e) => [e.id, e.name]));
    buildForm(meta);
    await loadLeaderboard(id);
    setStatus(`${cfg.label} ready — ${meta.attributes.length} attributes, ${meta.skills.length} skills`);
  } catch (err) {
    setStatus(`Failed to load ${cfg.label}: ${err.message}`, true);
    console.error(err);
  }
}

async function loadLeaderboard(rulesetId) {
  leaderboardBody.innerHTML = '';
  leaderboardNote.textContent = '';
  let data;
  try {
    const res = await fetch(`data/${rulesetId}_elo.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    leaderboardNote.textContent =
      'Leaderboard not found — it is generated by CI (scripts/elo_ranking.py --json). ' +
      'Run it locally and place the JSON in data/ to preview.';
    leaderboard = [];
    leaderboardMeta = '';
    leaderboardInitial = ELO_STANDARD; // no leaderboard, so fall back to the ELO standard
    return;
  }
  leaderboard = data.entries
    .map((e) => ({ ...e, name: entriesByName.get(e.id) ?? e.id }))
    .sort((a, b) => a.rank - b.rank);
  leaderboardInitial = data.initial ?? ELO_STANDARD; // the leaderboard's own ELO anchor
  leaderboardMeta =
    `${data.entries.length} combatants · ${data.rounds} rounds × ${data.games_per_pair} games/pair · ` +
    `start ${leaderboardInitial} · seed ${data.seed} · champion: ${data.champion}`;
  renderLeaderboard();
}

// ---------------------------------------------------------------------------
// leaderboard rendering + selection
// ---------------------------------------------------------------------------

/** Every row the table can show: the stored leaderboard plus the ranked
 *  character ("You") when present. */
function allEntries() {
  return [...leaderboard, ...(you ? [{ ...you, isYou: true }] : [])];
}

function entryById(id) {
  return allEntries().find((e) => e.id === id);
}

/** Reference for the relative "Win %" column: the single selected combatant
 *  (if exactly one row is ticked), or the generated character when nothing is
 *  selected — otherwise null, which keeps the stored win rate. */
function winPctReference() {
  if (selection.length === 1) return entryById(selection[0]) ?? null;
  if (selection.length === 0 && you) return you;
  return null;
}

function renderLeaderboard() {
  leaderboardBody.innerHTML = '';
  const reference = winPctReference();
  const rows = [...leaderboard];
  if (you) {
    const youRow = {
      rank: null, id: 'you', name: you.name, rating: you.rating,
      games: you.games, wins: you.wins, losses: you.losses, draws: you.draws,
      win_pct: you.games ? (100 * you.wins) / you.games : 0, isYou: true,
    };
    rows.push(youRow);
  }
  rows.sort((a, b) => b.rating - a.rating);
  rows.forEach((entry) => {
    const tr = document.createElement('tr');
    if (entry.isYou) tr.classList.add('you');
    if (selection.includes(entry.id)) tr.classList.add('selected');

    const rankTd = document.createElement('td');
    rankTd.className = 'num';
    rankTd.textContent = entry.isYou ? '—' : String(entry.rank);
    if (entry.rank === 1) rankTd.classList.add('rank-1');

    const nameTd = document.createElement('td');
    nameTd.textContent = entry.name;
    if (entry.isYou) {
      const badge = document.createElement('span');
      badge.className = 'badge';
      badge.textContent = 'YOU';
      nameTd.append(badge);
    }

    const num = (v, cls) => {
      const td = document.createElement('td');
      td.className = 'num';
      if (cls) td.className += ` ${cls}`;
      td.textContent = v;
      return td;
    };

    // Win % against the reference (a single selected row, or the ranked
    // character); the reference itself therefore shows exactly 50%.
    const winPct = reference
      ? expectedScore(entry.rating, reference.rating) * 100
      : entry.win_pct;

    const pickTd = document.createElement('td');
    pickTd.className = 'pick';
    const box = document.createElement('input');
    box.type = 'checkbox';
    box.checked = selection.includes(entry.id);
    box.addEventListener('click', (ev) => ev.stopPropagation());
    box.addEventListener('change', () => toggleSelection(entry.id));
    pickTd.append(box);

    tr.append(rankTd, nameTd,
      num(Math.round(entry.rating), 'rating'), num(entry.wins), num(entry.losses),
      num(entry.draws), num(winPct.toFixed(1)), pickTd);
    tr.addEventListener('click', () => toggleSelection(entry.id));
    leaderboardBody.append(tr);
  });

  const winNote = reference
    ? `Win % is an ELO estimate of relative strength (vs ${reference.name})`
    : "Win % is each combatant's actual win rate in the ranking tournament";
  leaderboardNote.textContent = `${leaderboardMeta} · ${winNote}`;
}

function toggleSelection(id) {
  duelLive = null; // a different pair means the stored live result is stale
  fightDetail = null;
  const idx = selection.indexOf(id);
  if (idx >= 0) {
    selection.splice(idx, 1);
  } else {
    selection.push(id);
    if (selection.length > 2) selection.shift(); // keep at most two
  }
  renderLeaderboard();
  renderDuel();
}

async function specForEntry(entry) {
  if (entry.isYou) return you.spec;
  return rpg.specFromId(entry.id);
}

/** Builds a `.duel` grid: two `.side`s (name, meta line, big probability) and
 *  a `.bar` that fills `leftPct`. Shared by the ELO estimate and the live
 *  Monte-Carlo result so the two are presented identically. */
function duelGrid(left, right, leftPct, { leftMeta, rightMeta } = {}) {
  const side = (entry, prob, cls, meta) => {
    const div = document.createElement('div');
    div.className = `side ${cls}`;
    const name = document.createElement('div');
    name.className = 'name';
    name.textContent = entry.name;
    const metaEl = document.createElement('div');
    metaEl.className = 'rating';
    metaEl.textContent = meta;
    const probEl = document.createElement('div');
    probEl.className = 'prob';
    probEl.textContent = `${(prob * 100).toFixed(1)}%`;
    div.append(name, metaEl, probEl);
    return div;
  };

  const wrap = document.createElement('div');
  wrap.className = 'duel';
  const vs = document.createElement('div');
  vs.className = 'vs';
  vs.textContent = 'vs';
  const bar = document.createElement('div');
  bar.className = 'bar';
  const fill = document.createElement('span');
  fill.style.width = `${(leftPct * 100).toFixed(1)}%`;
  bar.append(fill);
  wrap.append(
    side(left, leftPct, 'a', leftMeta ?? `ELO ${Math.round(left.rating)}`),
    vs,
    side(right, 1 - leftPct, 'b', rightMeta ?? `ELO ${Math.round(right.rating)}`),
    bar,
  );
  return wrap;
}

function renderDuel() {
  const el = $('#duel-result');
  if (selection.length !== 2) {
    el.innerHTML = '';
    duelLive = null;
    fightDetail = null;
    $('#duel-hint').textContent =
      selection.length === 1 ? 'Pick one more row to compare.' : 'Select two rows in the ranking to see the ELO win probability.';
    return;
  }
  $('#duel-hint').textContent = '';

  const [idA, idB] = selection;
  const a = entryById(idA);
  const b = entryById(idB);
  if (!a || !b) return;

  el.innerHTML = '';

  const label = (text) => {
    const l = document.createElement('div');
    l.className = 'duel-label';
    l.textContent = text;
    return l;
  };

  // What the ELO ratings suggest — an estimate: individual matchups can differ
  // from it, so the live fights below are the measured result.
  const pa = expectedScore(a.rating, b.rating);
  const predict = document.createElement('div');
  predict.append(label('ELO estimate'));
  predict.append(duelGrid(a, b, pa));
  const estimateNote = document.createElement('p');
  estimateNote.className = 'muted';
  estimateNote.textContent =
    'Estimate from the ELO ratings — individual matchups can differ from it. ' +
    'Run the live fights below for the measured result.';
  predict.append(estimateNote);

  // The live WASM confirmation; stays around so it can be re-run.
  const actions = document.createElement('div');
  actions.className = 'duel-actions';
  const button = document.createElement('button');
  button.textContent = duelLive ? 'Re-run 100 live fights' : 'Confirm with 100 live fights';
  button.addEventListener('click', () => runMonteCarlo(a, b, button));
  actions.append(button);

  // A single fight, replayed dice by dice: what happened each round and which
  // hit decided the winner.
  const detailButton = document.createElement('button');
  detailButton.className = 'ghost';
  detailButton.textContent = 'Run 1 fight — show details';
  detailButton.addEventListener('click', () => runSingleFight(a, b, detailButton));
  actions.append(detailButton);

  el.append(predict, actions);

  // The live result, in the same layout as the prediction (with real names).
  if (duelLive) {
    const { winsA, winsB, draws } = duelLive;
    const total = winsA + winsB + draws;
    const live = document.createElement('div');
    live.append(label(`Live result — ${total} fights (WASM)`));
    live.append(duelGrid(a, b, (winsA + 0.5 * draws) / total, {
      leftMeta: `${winsA}W · ${draws}D · ${winsB}L`,
      rightMeta: `${winsB}W · ${draws}D · ${winsA}L`,
    }));
    el.append(live);
  }

  // The transcript of the last single detailed fight, if one was run.
  if (fightDetail) {
    el.append(renderFightDetail(a, b));
  }
}

async function runMonteCarlo(a, b, button) {
  button.disabled = true;
  const originalLabel = button.textContent;
  button.textContent = 'Simulating…';
  let winsA = 0;
  let winsB = 0;
  let draws = 0;
  try {
    const specA = await specForEntry(a);
    const specB = await specForEntry(b);
    // Each run is a fresh Monte-Carlo sample, so re-running shows how the
    // measured result varies around the ELO estimate (fights within a run stay
    // distinct via the index, mirroring scripts/elo_ranking.py).
    const runSeed = Math.floor(Math.random() * SEED_MOD) >>> 0;
    for (let i = 0; i < LIVE_FIGHTS; i += 1) {
      const seed = (runSeed * SEED_MUL + i * SEED_STRIDE + SEED_ADD) >>> 0;
      const outcome = rpg.fight(specA, specB, { seed, maxRounds: MAX_ROUNDS });
      if (outcome.winner_index === 0) winsA += 1;
      else if (outcome.winner_index === 1) winsB += 1;
      else draws += 1;
    }
    if (!a.isYou) specA.dispose();
    if (!b.isYou) specB.dispose();
  } catch (err) {
    setStatus(`Live fight failed: ${err.message}`, true);
    console.error(err);
    button.disabled = false;
    button.textContent = originalLabel;
    return;
  }
  duelLive = { winsA, winsB, draws };
  renderDuel();
}

/** Runs a single fight between the two combatants and stores its transcript
 *  for rendering. Each run draws fresh dice, so the replay varies like the
 *  live Monte-Carlo result does. */
async function runSingleFight(a, b, button) {
  button.disabled = true;
  const originalLabel = button.textContent;
  button.textContent = 'Simulating…';
  try {
    const specA = await specForEntry(a);
    const specB = await specForEntry(b);
    const seed = Math.floor(Math.random() * SEED_MOD) >>> 0;
    fightDetail = rpg.fightDetail(specA, specB, { seed, maxRounds: MAX_ROUNDS });
    if (!a.isYou) specA.dispose();
    if (!b.isYou) specB.dispose();
  } catch (err) {
    setStatus(`Fight detail failed: ${err.message}`, true);
    console.error(err);
    button.disabled = false;
    button.textContent = originalLabel;
    return;
  }
  renderDuel();
}

// ---------------------------------------------------------------------------
// single-fight transcript rendering (renderFightRound comes from transcript.js)
// ---------------------------------------------------------------------------

/** The transcript of the last single fight, from the opening roll to the
 *  winner. Extremely long (draw) fights are truncated in the middle so the
 *  beginning and the end stay readable. */
function renderFightDetail(a, b) {
  const detail = fightDetail;
  const block = document.createElement('div');
  block.className = 'fight-detail';

  const labelEl = document.createElement('div');
  labelEl.className = 'duel-label';
  labelEl.textContent = 'Fight details';
  block.append(labelEl);

  const hpPool = detail.hp_pool;
  const aName = a.name;
  const bName = b.name;
  const winnerName = detail.winner_index === 0 ? aName : detail.winner_index === 1 ? bName : null;

  const summary = document.createElement('div');
  summary.className = 'fight-summary';
  const outcome = document.createElement('b');
  outcome.className = winnerName ? 'fight-winner' : 'fight-draw';
  outcome.textContent = `${winnerName ? '🏆 ' : '🤝 '}${winnerName
    ? `${winnerName} wins in ${detail.rounds} round${detail.rounds === 1 ? '' : 's'}`
    : `Draw after ${detail.rounds} rounds`}`;
  summary.append(outcome);
  // Each spellcaster's starting spell resource (e.g. "(AE 35)") — shown only
  // for combatants that actually know spells, so a pure-melee creature with a
  // dormant pool doesn't get a spurious note. The per-cast lines then show it
  // running down.
  const resourceId = detail.log?.resource_id;
  const resourceNote = (index) =>
    resourceId && detail.log?.spells?.[index]?.length > 0 && detail.log.resource_pool[index] > 0
      ? ` (${resourceId} ${detail.log.resource_pool[index]})`
      : '';
  summary.append(document.createTextNode(
    ` · ${aName} ${detail.max_lp[0]} → ${detail.remaining_lp[0]} ${hpPool}${resourceNote(0)}` +
    ` · ${bName} ${detail.max_lp[1]} → ${detail.remaining_lp[1]} ${hpPool}${resourceNote(1)}`));
  block.append(summary);

  // Which combatants are spellcasters and what they can cast (only shown when
  // at least one side knows a spell).
  const spells = detail.log?.spells;
  const known = renderKnownSpells(aName, spells?.[0], bName, spells?.[1]);
  if (known) block.append(known);

  const roundsEl = document.createElement('div');
  roundsEl.className = 'fight-rounds';
  const all = detail.log.rounds;
  const cap = 60; // keep an extreme (draw) fight readable
  const shown = all.length > 2 * cap
    ? [...all.slice(0, cap), null, ...all.slice(all.length - cap)]
    : all;
  for (const round of shown) {
    if (round === null) {
      const gap = document.createElement('div');
      gap.className = 'fight-gap';
      gap.textContent = `… ${all.length - 2 * cap} rounds omitted …`;
      roundsEl.append(gap);
      continue;
    }
    roundsEl.append(renderFightRound(round, aName, bName, hpPool));
  }
  block.append(roundsEl);
  return block;
}

// ---------------------------------------------------------------------------
// character form
// ---------------------------------------------------------------------------

function clearForm() {
  $('#form-fields').innerHTML = '';
  $('#rank-result').hidden = true;
  $('#rank-result').innerHTML = '';
}

function buildForm(m) {
  const fields = $('#form-fields');
  fields.innerHTML = '';

  // Class (archetype) selector: pre-fills attributes/skills/spells from a
  // ruleset archetype as a starting point ("Custom character" to edit freely).
  // Rulesets without archetypes (D&D) skip this and only get the spell picker.
  if (archetypes.length > 0) {
    const classHeading = document.createElement('h3');
    classHeading.textContent = 'Class';
    fields.append(classHeading);
    const classField = document.createElement('label');
    classField.className = 'stat-field';
    const classLabel = document.createElement('span');
    classLabel.textContent = 'Start from an archetype (edit freely after)';
    const classSelect = document.createElement('select');
    classSelect.name = 'class';
    const custom = document.createElement('option');
    custom.value = '';
    custom.textContent = 'Custom character';
    classSelect.append(custom);
    for (const arch of archetypes) {
      const opt = document.createElement('option');
      opt.value = arch.id;
      opt.textContent = arch.name;
      classSelect.append(opt);
    }
    classSelect.addEventListener('change', () => applyArchetype(classSelect.value));
    classField.append(classLabel, classSelect);
    fields.append(classField);
  }

  // Attributes
  const attrsHeading = document.createElement('h3');
  attrsHeading.textContent = 'Attributes';
  fields.append(attrsHeading);
  const attrsGrid = document.createElement('div');
  attrsGrid.className = 'grid';
  for (const attr of m.attributes) {
    attrsGrid.append(statInput(`attr:${attr.id}`, attr.name, attr.default, attr.min, attr.max));
  }
  fields.append(attrsGrid);

  // Skills (collapsible)
  const details = document.createElement('details');
  details.className = 'skills';
  const summary = document.createElement('summary');
  summary.textContent = `Skills (${m.skills.length})`;
  details.append(summary);
  const skillsGrid = document.createElement('div');
  skillsGrid.className = 'grid';
  for (const skill of m.skills) {
    skillsGrid.append(statInput(`skill:${skill.id}`, skill.name, skill.default, 0, 25));
  }
  details.append(skillsGrid);
  fields.append(details);

  // Spells (collapsible picker): which spells the character knows. Only
  // damaging spells are actually cast by the fight simulator, so those are
  // listed first and marked; the others are still selectable (a known-but-
  // never-cast spell is still part of the sheet).
  buildSpellPicker(fields);

  // Combat: weapon + derived readout + optional overrides.
  const combatHeading = document.createElement('h3');
  combatHeading.textContent = 'Combat';
  fields.append(combatHeading);
  const weaponField = document.createElement('label');
  weaponField.className = 'stat-field';
  weaponField.innerHTML = `<span>Weapon damage</span>`;
  const weaponInput = document.createElement('input');
  weaponInput.name = 'weapon';
  weaponInput.value = DEFAULT_WEAPON;
  weaponInput.setAttribute('aria-label', 'Weapon damage dice');
  weaponField.append(weaponInput);
  fields.append(weaponField);

  // Optional combat overrides. Left blank they use the derived value; fill one
  // to override it (e.g. D&D has no derived Attack, so set your to-hit here).
  const overrides = document.createElement('div');
  overrides.className = 'grid';
  overrides.id = 'combat-overrides';
  for (const stat of COMBAT_STATS) {
    overrides.append(overrideInput(`combat:${stat}`, stat, `${stat} (optional override)`));
  }
  // Optional spell-resource override (e.g. a TDE mage's real AE, not just the
  // derived maximum). Without it the sheet starts at the derived pool.
  const spellResource = meta?.spell_resource;
  if (spellResource) {
    overrides.append(overrideInput(`resource:${spellResource}`, spellResource,
      `${spellResource} (optional override)`));
  }
  fields.append(overrides);

  const readout = document.createElement('div');
  readout.className = 'readout';
  readout.id = 'combat-readout';
  readout.textContent = 'Derived combat values update as you type…';
  fields.append(readout);

  fields.addEventListener('input', () => {
    clearTimeout(formDebounce);
    formDebounce = setTimeout(refreshDerived, 150);
  });
  refreshDerived();
}

function statInput(key, labelText, value, min, max) {
  const wrap = document.createElement('label');
  wrap.className = 'stat-field';
  const label = document.createElement('span');
  label.textContent = labelText;
  const input = document.createElement('input');
  input.type = 'number';
  input.name = key;
  input.value = String(value);
  input.min = String(min ?? 0);
  input.max = String(max ?? 25);
  input.setAttribute('aria-label', labelText);
  wrap.append(label, input);
  return wrap;
}

/** An optional (blank = auto) numeric override field. */
function overrideInput(name, labelText, ariaLabel) {
  const wrap = document.createElement('label');
  wrap.className = 'stat-field';
  const label = document.createElement('span');
  label.textContent = labelText;
  const input = document.createElement('input');
  input.type = 'number';
  input.name = name;
  input.placeholder = 'auto';
  input.setAttribute('aria-label', ariaLabel);
  wrap.append(label, input);
  return wrap;
}

/** An archetype ("class") shaped for the form's pre-fill. */
function archetypeSummary(arch) {
  return {
    id: arch.id,
    name: arch.name ?? arch.id,
    attributes: arch.attributes ?? {},
    skills: arch.skills ?? {},
    spells_known: arch.spells_known ?? [],
  };
}

/** The spells a character can know, shaped for the picker. Mirrors the
 *  engine's spellAverageDamage (combat.hpp): only `effects[].kind ===
 *  "damage"` dice count — a spell with no damage is never cast in a fight,
 *  so it is marked as non-damaging. */
function spellSummary(spell) {
  let damageDice = null;
  if (Array.isArray(spell.effects) && spell.effects.length > 0) {
    const dmg = spell.effects.find((e) => e && e.kind === 'damage' && e.dice != null);
    damageDice = dmg ? dmg.dice : null;
  } else if (spell.damage != null) {
    damageDice = spell.damage;
  }
  const level = spell.level ?? '';
  const cost = spell.cost ?? spell.ae_cost ?? '';
  return {
    id: spell.id,
    name: spell.name ?? spell.id,
    levelTag: level !== '' ? ` · L${level}` : '',
    costTag: cost !== '' ? ` · ${cost}` : '',
    damageTag: damageDice != null ? ` · ${damageDice}` : '',
    damaging: damageDice != null,
    classes: spell.classes ?? [],
    traditions: spell.traditions ?? [],
  };
}

/** Ids of the spells currently checked in the form. */
function knownSpellIds() {
  return [...document.querySelectorAll('#form-fields input[name^="spell:"]:checked')]
    .map((cb) => cb.name.slice(cb.name.indexOf(':') + 1));
}

/** Distinct classes (D&D) or traditions (TDE) the ruleset's spells carry —
 *  the group filter options for the spell picker. */
function spellGroups() {
  const groups = new Set();
  for (const s of spells) {
    for (const g of (s.classes ?? []).concat(s.traditions ?? [])) groups.add(g);
  }
  return [...groups].sort();
}

/** The "Spells" section of the form: a searchable/filterable checkbox list of
 *  every spell in the ruleset, plus a note that only damaging spells are cast
 *  by the fight simulator (the engine's pickSpell only ever chooses spells
 *  that deal damage and are affordable). */
function buildSpellPicker(fields) {
  if (spells.length === 0) return; // ruleset has no spells → pure melee
  const details = document.createElement('details');
  details.className = 'skills spells';
  const summary = document.createElement('summary');
  summary.textContent = `Spells (${knownSpellIds().length} selected)`;
  details.append(summary);

  const hint = document.createElement('p');
  hint.className = 'hint spell-hint';
  hint.textContent = 'Known spells of your character — only damaging spells are cast in test fights.';
  details.append(hint);

  const filterRow = document.createElement('div');
  filterRow.className = 'spell-filters';
  const filter = document.createElement('input');
  filter.type = 'search';
  filter.className = 'spell-filter';
  filter.placeholder = 'Filter spells…';
  filter.setAttribute('aria-label', 'Filter spells');
  filterRow.append(filter);

  // A class/tradition filter when the spells carry one (D&D classes, TDE
  // traditions) — keeps a large spell list manageable.
  const groups = spellGroups();
  let groupSelect = null;
  if (groups.length > 1) {
    groupSelect = document.createElement('select');
    groupSelect.className = 'spell-group';
    const all = document.createElement('option');
    all.value = '';
    all.textContent = 'All';
    groupSelect.append(all);
    for (const g of groups) {
      const opt = document.createElement('option');
      opt.value = g;
      opt.textContent = g;
      groupSelect.append(opt);
    }
    filterRow.append(groupSelect);
  }
  details.append(filterRow);

  const grid = document.createElement('div');
  grid.className = 'grid spells-grid';
  for (const s of [...spells].sort((a, b) => Number(b.damaging) - Number(a.damaging))) {
    const label = document.createElement('label');
    label.className = 'spell-item';
    label.dataset.damaging = s.damaging ? '1' : '0';
    label.dataset.group = (s.classes ?? []).concat(s.traditions ?? []).join('|');
    const cb = document.createElement('input');
    cb.type = 'checkbox';
    cb.name = `spell:${s.id}`;
    const span = document.createElement('span');
    span.textContent = `${s.name}${s.levelTag}${s.costTag}${s.damageTag}`;
    label.append(cb, span);
    grid.append(label);
  }
  details.append(grid);

  // Filtering: the text filter matches the spell's label; the group select
  // narrows to a class (D&D) or tradition (TDE).
  const applyFilter = () => {
    const text = filter.value.trim().toLowerCase();
    const group = groupSelect ? groupSelect.value : '';
    for (const item of grid.querySelectorAll('.spell-item')) {
      const matchesText = !text || item.textContent.toLowerCase().includes(text);
      const matchesGroup = !group || (item.dataset.group ?? '').split('|').includes(group);
      item.hidden = !(matchesText && matchesGroup);
    }
  };
  filter.addEventListener('input', applyFilter);
  groupSelect?.addEventListener('change', applyFilter);

  // Keep the count and the derived readout fresh when spells are picked.
  grid.addEventListener('change', () => {
    summary.textContent = `Spells (${knownSpellIds().length} selected)`;
    refreshDerived();
  });

  fields.append(details);
}

/** Pre-fills the form (attributes, skills, spells) from an archetype; a
 *  "Custom character" selection (empty id) leaves the form as it is.
 *  D&D archetypes are class shells without attributes/skills/spells_known, so
 *  the optional fields are guarded (selecting one just leaves the form as-is). */
function applyArchetype(id) {
  const arch = archetypes.find((a) => a.id === id);
  if (!arch) return;
  const set = (prefix, values) => {
    for (const [key, value] of Object.entries(values ?? {})) {
      const input = document.querySelector(`#form-fields input[name="${prefix}:${key}"]`);
      if (input) input.value = value;
    }
  };
  set('attr', arch.attributes);
  set('skill', arch.skills);
  const known = arch.spells_known ?? [];
  for (const cb of document.querySelectorAll('#form-fields input[name^="spell:"]')) {
    cb.checked = known.includes(cb.name.slice(cb.name.indexOf(':') + 1));
  }
  const spellSummaryEl = document.querySelector('.spells summary');
  if (spellSummaryEl) spellSummaryEl.textContent = `Spells (${knownSpellIds().length} selected)`;
  refreshDerived();
}

/** The derived maximum of a resource pool (e.g. TDE's AE = 20 + INT), read
 *  from a fresh probe entity — a new pool starts at its full derived maximum,
 *  so getResource returns the cap the engine will enforce on any spend. */
function derivedResourceMax(pool) {
  try {
    const probe = rpg.createEntityFromSheet('probe', { stats: collectStats() });
    const max = probe.getResource(pool);
    probe.dispose();
    return max;
  } catch {
    return Number.MAX_SAFE_INTEGER;
  }
}

/** The full sheet a ranked character is built from: the collected stats, the
 *  selected spells as a spellbook (so makeCombatantSpecFromEntity sees them),
 *  and an optional spell-resource override (e.g. a TDE mage's actual AE). */
function collectSheet() {
  const stats = collectStats();
  const sheet = { stats };
  const known = knownSpellIds();
  if (known.length > 0) {
    sheet.spellbook = { known };
  }
  const resource = meta?.spell_resource;
  if (resource) {
    const input = document.querySelector(`#form-fields input[name="resource:${resource}"]`);
    if (input && input.value.trim() !== '') {
      const value = Number(input.value);
      if (!Number.isNaN(value)) {
        // The pool is clamped to its derived maximum on any spend, so an
        // override above it would read as a confusing "AE 60 → 35" in the
        // transcript. Clamp it up front to what the engine will actually
        // let the sheet have.
        sheet.resources = { [resource]: Math.max(0, Math.min(value, derivedResourceMax(resource))) };
      }
    }
  }
  return sheet;
}

function collectStats() {
  const stats = {};
  for (const input of document.querySelectorAll('#form-fields input[name^="attr:"], #form-fields input[name^="skill:"]')) {
    const value = Number(input.value);
    if (!Number.isNaN(value)) stats[input.name.slice(input.name.indexOf(':') + 1)] = value;
  }
  // Combat overrides are optional: only a non-empty value overrides the derived stat.
  for (const input of document.querySelectorAll('#form-fields input[name^="combat:"]')) {
    if (input.value.trim() !== '') {
      const value = Number(input.value);
      if (!Number.isNaN(value)) stats[input.name.slice(input.name.indexOf(':') + 1)] = value;
    }
  }
  return stats;
}

function currentWeapon() {
  return document.querySelector('#form-fields input[name="weapon"]')?.value || DEFAULT_WEAPON;
}

/** Live readout: derived combat values (and spell resource) of the character
 *  as typed so far. */
function refreshDerived() {
  const readout = $('#combat-readout');
  if (!readout || !rpg) return;
  try {
    const probe = rpg.createEntityFromSheet('probe', collectSheet());
    const hpPool = meta.resource_pools[0]?.id;
    const values = COMBAT_STATS.map((s) => {
      const v = probe.getStat(s);
      return `<b>${s}</b> ${v}`;
    });
    const hp = hpPool ? `<b>${hpPool}</b> ${probe.getResource(hpPool)}` : '';
    const sr = meta?.spell_resource;
    const res = sr ? `<b>${sr}</b> ${probe.getResource(sr)}` : '';
    readout.innerHTML =
      `Derived: ${values.join(' · ')}${hp ? ` · ${hp}` : ''}${res ? ` · ${res}` : ''}`;
    probe.dispose();
  } catch (err) {
    readout.textContent = 'Enter attributes to see derived combat values.';
  }
}

async function rankCharacter(event) {
  event.preventDefault();
  const button = $('#rank-btn');
  const progress = $('#rank-progress');
  button.disabled = true;
  progress.hidden = false;
  try {
    you?.spec?.dispose();
    const entity = rpg.createEntityFromSheet('you', collectSheet());
    const spec = rpg.specFromEntity(entity, currentWeapon());
    entity.dispose();

    const opponents = leaderboard.map((e) => ({ id: e.id, rating: e.rating }));

    const result = await rankNewcomer(rpg, spec, opponents, {
      gamesPerOpponent: GAMES_PER_OPPONENT,
      opponentsPerRound: RANK_OPPONENTS_PER_ROUND,
      rounds: RANK_ROUNDS,
      initial: leaderboardInitial,
    });
    you = {
      id: 'you',
      name: 'You',
      rating: result.rating,
      spec,
      wins: result.wins,
      losses: result.losses,
      draws: result.draws,
      games: result.games,
    };
    renderRankResult(result);
    selection = [];
    renderLeaderboard();
    renderDuel();
  } catch (err) {
    setStatus(`Ranking failed: ${err.message}`, true);
    console.error(err);
  } finally {
    button.disabled = false;
    progress.hidden = true;
  }
}

function renderRankResult(result) {
  const box = $('#rank-result');
  box.hidden = false;
  const rank = [...leaderboard].filter((e) => e.rating > result.rating).length + 1;
  box.innerHTML =
    `<div class="big">ELO ${Math.round(result.rating)}</div>` +
    `<p>Ranked Swiss-style against the ${result.opponents} leaderboard combatants ` +
    `closest to your rating (${GAMES_PER_OPPONENT} fights each, K=${ELO_K}, ` +
    `start ${leaderboardInitial}): ` +
    `${result.wins}W / ${result.losses}L / ${result.draws}D. ` +
    `That places you at <b>#${rank}</b> in the table. ` +
    `You are now selectable for a head-to-head below.</p>`;
  box.classList.remove('warn');
  box.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

// ---------------------------------------------------------------------------

$('#char-form').addEventListener('submit', rankCharacter);

initEngine().catch((err) => console.error(err));
