// Copyright (c) 2026 Christian Mayer and the Mundus Mirabilis contributors.
// SPDX-License-Identifier: Apache-2.0

/**
 * The ELO Arena demo: a leaderboard of the shipped rulesets (generated by the
 * Python Monte-Carlo ELO script during CI), a form to enter an arbitrary
 * character that is then ranked live by the WASM engine + the JS ELO formula,
 * and a head-to-head panel that computes fight-win probabilities from ELO
 * ratings (with an optional live Monte-Carlo confirmation).
 *
 * The page is plain ES modules — no build step. At deploy time the CI copies
 * the WASM assets into ./wasm/, the rulesets into ./rulesets/, and writes the
 * leaderboards into ./data/ (all three folders are gitignored here).
 */
import { init } from './rpg-browser.js';
import { expectedScore, winProbability, rankNewcomer } from './elo.js';

const RULESETS = {
  tde5e_core: { label: 'The Dark Eye 5e', file: 'tde5e_core.json' },
  dnd5e_srd: { label: 'D&D 5e SRD', file: 'dnd5e_srd.json' },
};

const COMBAT_STATS = ['Attack', 'Parry', 'Armor_Rating', 'AC', 'Initiative'];
const RANK_OPPONENTS = 16; // the newcomer fights the top-N entries
const GAMES_PER_OPPONENT = 20;

const $ = (sel) => document.querySelector(sel);
const status = $('#status');
const leaderboardBody = $('#leaderboard-body');
const leaderboardNote = $('#leaderboard-note');

let rpg = null;
let meta = null;
let entriesByName = new Map(); // id -> display name (from the ruleset)
let leaderboard = []; // [{rank,id,name,rating,games,wins,losses,draws,win_pct}]
let you = null; // { name, rating, spec } for the ranked character (spec kept alive)
let selection = []; // ids of the selected rows (max 2)
let formDebounce = 0;

function setStatus(text, isError = false) {
  status.textContent = text;
  status.classList.toggle('error', isError);
}

// ---------------------------------------------------------------------------
// init / ruleset loading
// ---------------------------------------------------------------------------

async function initEngine() {
  setStatus('Loading engine…');
  try {
    rpg = await init();
  } catch (err) {
    setStatus(`Engine failed to load: ${err.message}`, true);
    throw err;
  }
  const select = $('#ruleset-select');
  for (const [id, cfg] of Object.entries(RULESETS)) {
    const opt = document.createElement('option');
    opt.value = id;
    opt.textContent = cfg.label;
    select.append(opt);
  }
  select.addEventListener('change', () => loadRuleset(select.value));
  await loadRuleset(select.value);
}

async function loadRuleset(id) {
  const cfg = RULESETS[id];
  setStatus(`Loading ${cfg.label}…`);
  clearForm();
  selection = [];
  you?.spec?.dispose();
  you = null;
  renderDuel();

  try {
    const rulesetJson = await (await fetch(`rulesets/${cfg.file}`)).text();
    rpg.loadRuleset(rulesetJson);
    meta = rpg.meta();
    const entries = rpg.entries();
    entriesByName = new Map(entries.map((e) => [e.id, e.name]));
    buildForm(meta);
    await loadLeaderboard(id);
    setStatus(`${cfg.label} ready — ${meta.attributes.length} attributes, ${meta.skills.length} skills`);
  } catch (err) {
    setStatus(`Failed to load ${cfg.label}: ${err.message}`, true);
    console.error(err);
  }
}

async function loadLeaderboard(rulesetId) {
  leaderboardBody.innerHTML = '';
  leaderboardNote.textContent = '';
  let data;
  try {
    const res = await fetch(`data/${rulesetId}_elo.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    leaderboardNote.textContent =
      'Leaderboard not found — it is generated by CI (scripts/elo_ranking.py --json). ' +
      'Run it locally and place the JSON in data/ to preview.';
    leaderboard = [];
    return;
  }
  leaderboard = data.entries
    .map((e) => ({ ...e, name: entriesByName.get(e.id) ?? e.id }))
    .sort((a, b) => a.rank - b.rank);
  leaderboardNote.textContent =
    `${data.entries.length} combatants · ${data.rounds} rounds × ${data.games_per_pair} games/pair · ` +
    `seed ${data.seed} · champion: ${data.champion}`;
  renderLeaderboard();
}

// ---------------------------------------------------------------------------
// leaderboard rendering + selection
// ---------------------------------------------------------------------------

function renderLeaderboard() {
  leaderboardBody.innerHTML = '';
  const rows = [...leaderboard];
  if (you) {
    const youRow = {
      rank: null, id: 'you', name: you.name, rating: you.rating,
      games: you.games, wins: you.wins, losses: you.losses, draws: you.draws,
      win_pct: you.games ? (100 * you.wins) / you.games : 0, isYou: true,
    };
    rows.push(youRow);
  }
  rows.sort((a, b) => b.rating - a.rating);
  rows.forEach((entry, index) => {
    const tr = document.createElement('tr');
    if (entry.isYou) tr.classList.add('you');
    if (selection.includes(entry.id)) tr.classList.add('selected');

    const rankTd = document.createElement('td');
    rankTd.className = 'num';
    rankTd.textContent = entry.isYou ? '—' : String(entry.rank);
    if (entry.rank === 1) rankTd.classList.add('rank-1');

    const nameTd = document.createElement('td');
    nameTd.textContent = entry.name;
    if (entry.isYou) {
      const badge = document.createElement('span');
      badge.className = 'badge';
      badge.textContent = 'YOU';
      nameTd.append(badge);
    }

    const num = (v, cls) => {
      const td = document.createElement('td');
      td.className = 'num';
      if (cls) td.className += ` ${cls}`;
      td.textContent = v;
      return td;
    };

    const pickTd = document.createElement('td');
    pickTd.className = 'pick';
    const box = document.createElement('input');
    box.type = 'checkbox';
    box.checked = selection.includes(entry.id);
    box.addEventListener('click', (ev) => ev.stopPropagation());
    box.addEventListener('change', () => toggleSelection(entry.id));
    pickTd.append(box);

    tr.append(rankTd, nameTd,
      num(Math.round(entry.rating), 'rating'), num(entry.wins), num(entry.losses),
      num(entry.draws), num(entry.win_pct.toFixed(1)), pickTd);
    tr.addEventListener('click', () => toggleSelection(entry.id));
    leaderboardBody.append(tr);
  });
}

function toggleSelection(id) {
  const idx = selection.indexOf(id);
  if (idx >= 0) {
    selection.splice(idx, 1);
  } else {
    selection.push(id);
    if (selection.length > 2) selection.shift(); // keep at most two
  }
  renderLeaderboard();
  renderDuel();
}

async function specForEntry(entry) {
  if (entry.isYou) return you.spec;
  return rpg.specFromId(entry.id);
}

function renderDuel() {
  const el = $('#duel-result');
  if (selection.length !== 2) {
    el.innerHTML = '';
    $('#duel-hint').textContent =
      selection.length === 1 ? 'Pick one more row to compare.' : 'Select two rows in the ranking to see the ELO win probability.';
    return;
  }
  $('#duel-hint').textContent = '';

  const [idA, idB] = selection;
  const find = (id) => [...leaderboard, ...(you ? [{ ...you, isYou: true }] : [])]
    .find((e) => e.id === id);
  const a = find(idA);
  const b = find(idB);
  if (!a || !b) return;

  const pa = winProbability(a.rating, b.rating);
  const pb = 1 - pa;

  el.innerHTML = '';
  const bar = document.createElement('div');
  bar.className = 'bar';
  const fill = document.createElement('span');
  fill.style.width = `${(pa * 100).toFixed(1)}%`;
  bar.append(fill);

  const side = (entry, prob, cls) => {
    const div = document.createElement('div');
    div.className = `side ${cls}`;
    div.innerHTML = `<div class="name"></div><div class="rating"></div><div class="prob"></div>`;
    div.querySelector('.name').textContent = entry.name;
    div.querySelector('.rating').textContent = `ELO ${Math.round(entry.rating)}`;
    div.querySelector('.prob').textContent = `${(prob * 100).toFixed(1)}%`;
    return div;
  };
  const vs = document.createElement('div');
  vs.className = 'vs';
  vs.textContent = 'vs';

  const button = document.createElement('button');
  button.textContent = 'Confirm with 100 live fights';
  button.addEventListener('click', () => runMonteCarlo(a, b, button));

  el.append(side(a, pa, 'a'), vs, side(b, pb, 'b'), bar, button);
}

async function runMonteCarlo(a, b, button) {
  button.disabled = true;
  button.textContent = 'Simulating…';
  const specA = await specForEntry(a);
  const specB = await specForEntry(b);
  let winsA = 0;
  let winsB = 0;
  let draws = 0;
  for (let i = 0; i < 100; i += 1) {
    const seed = (i * 1000003 + 13) >>> 0;
    const outcome = rpg.fight(specA, specB, { seed, maxRounds: 1000 });
    if (outcome.winner_index === 0) winsA += 1;
    else if (outcome.winner_index === 1) winsB += 1;
    else draws += 1;
  }
  if (!a.isYou) specA.dispose();
  if (!b.isYou) specB.dispose();
  const note = document.createElement('p');
  note.className = 'muted';
  note.textContent =
    `Live: ${winsA} A / ${winsB} B / ${draws} draws (100 fights, WASM). ` +
    `ELO prediction: A ${(winProbability(a.rating, b.rating) * 100).toFixed(1)}%.`;
  button.replaceWith(note);
}

// ---------------------------------------------------------------------------
// character form
// ---------------------------------------------------------------------------

function clearForm() {
  $('#form-fields').innerHTML = '';
  $('#rank-result').hidden = true;
  $('#rank-result').innerHTML = '';
}

function buildForm(m) {
  const fields = $('#form-fields');
  fields.innerHTML = '';

  // Attributes
  const attrsHeading = document.createElement('h3');
  attrsHeading.textContent = 'Attributes';
  fields.append(attrsHeading);
  const attrsGrid = document.createElement('div');
  attrsGrid.className = 'grid';
  for (const attr of m.attributes) {
    attrsGrid.append(statInput(`attr:${attr.id}`, attr.name, attr.default, attr.min, attr.max));
  }
  fields.append(attrsGrid);

  // Skills (collapsible)
  const details = document.createElement('details');
  details.className = 'skills';
  const summary = document.createElement('summary');
  summary.textContent = `Skills (${m.skills.length})`;
  details.append(summary);
  const skillsGrid = document.createElement('div');
  skillsGrid.className = 'grid';
  for (const skill of m.skills) {
    skillsGrid.append(statInput(`skill:${skill.id}`, skill.name, skill.default, 0, 25));
  }
  details.append(skillsGrid);
  fields.append(details);

  // Combat: weapon + derived readout + optional overrides.
  const combatHeading = document.createElement('h3');
  combatHeading.textContent = 'Combat';
  fields.append(combatHeading);
  const weaponField = document.createElement('label');
  weaponField.className = 'stat-field';
  weaponField.innerHTML = `<span>Weapon damage</span>`;
  const weaponInput = document.createElement('input');
  weaponInput.name = 'weapon';
  weaponInput.value = '1d6+4';
  weaponInput.setAttribute('aria-label', 'Weapon damage dice');
  weaponField.append(weaponInput);
  fields.append(weaponField);

  // Optional combat overrides. Left blank they use the derived value; fill one
  // to override it (e.g. D&D has no derived Attack, so set your to-hit here).
  const overrides = document.createElement('div');
  overrides.className = 'grid';
  overrides.id = 'combat-overrides';
  for (const stat of COMBAT_STATS) {
    const wrap = document.createElement('label');
    wrap.className = 'stat-field';
    const label = document.createElement('span');
    label.textContent = stat;
    const input = document.createElement('input');
    input.type = 'number';
    input.name = `combat:${stat}`;
    input.placeholder = 'auto';
    input.setAttribute('aria-label', `${stat} (optional override)`);
    wrap.append(label, input);
    overrides.append(wrap);
  }
  fields.append(overrides);

  const readout = document.createElement('div');
  readout.className = 'readout';
  readout.id = 'combat-readout';
  readout.textContent = 'Derived combat values update as you type…';
  fields.append(readout);

  fields.addEventListener('input', () => {
    clearTimeout(formDebounce);
    formDebounce = setTimeout(refreshDerived, 150);
  });
  refreshDerived();
}

function statInput(key, labelText, value, min, max) {
  const wrap = document.createElement('label');
  wrap.className = 'stat-field';
  const label = document.createElement('span');
  label.textContent = labelText;
  const input = document.createElement('input');
  input.type = 'number';
  input.name = key;
  input.value = String(value);
  input.min = String(min ?? 0);
  input.max = String(max ?? 25);
  input.setAttribute('aria-label', labelText);
  wrap.append(label, input);
  return wrap;
}

function collectStats() {
  const stats = {};
  for (const input of document.querySelectorAll('#form-fields input[name^="attr:"], #form-fields input[name^="skill:"]')) {
    const value = Number(input.value);
    if (!Number.isNaN(value)) stats[input.name.slice(input.name.indexOf(':') + 1)] = value;
  }
  // Combat overrides are optional: only a non-empty value overrides the derived stat.
  for (const input of document.querySelectorAll('#form-fields input[name^="combat:"]')) {
    if (input.value.trim() !== '') {
      const value = Number(input.value);
      if (!Number.isNaN(value)) stats[input.name.slice(input.name.indexOf(':') + 1)] = value;
    }
  }
  return stats;
}

function currentWeapon() {
  return document.querySelector('#form-fields input[name="weapon"]')?.value || '1d6+4';
}

/** Live readout: derived combat values of the character as typed so far. */
function refreshDerived() {
  const readout = $('#combat-readout');
  if (!readout || !rpg) return;
  try {
    const stats = collectStats();
    const probe = rpg.createEntityFromSheet('probe', stats);
    const hpPool = meta.resource_pools[0]?.id;
    const values = COMBAT_STATS.map((s) => {
      const v = probe.getStat(s);
      return `<b>${s}</b> ${v}`;
    });
    const hp = hpPool ? `<b>${hpPool}</b> ${probe.getResource(hpPool)}` : '';
    readout.innerHTML = `Derived: ${values.join(' · ')}${hp ? ` · ${hp}` : ''}`;
    probe.dispose();
  } catch (err) {
    readout.textContent = 'Enter attributes to see derived combat values.';
  }
}

async function rankCharacter(event) {
  event.preventDefault();
  const button = $('#rank-btn');
  const progress = $('#rank-progress');
  button.disabled = true;
  progress.hidden = false;
  try {
    you?.spec?.dispose();
    const stats = collectStats();
    const entity = rpg.createEntityFromSheet('you', stats);
    const spec = rpg.specFromEntity(entity, currentWeapon());
    entity.dispose();

    const opponents = leaderboard
      .slice(0, RANK_OPPONENTS)
      .map((e) => ({ id: e.id, rating: e.rating }));

    const result = await rankNewcomer(rpg, spec, opponents, {
      gamesPerOpponent: GAMES_PER_OPPONENT,
    });
    you = {
      id: 'you',
      name: 'You',
      rating: result.rating,
      spec,
      wins: result.wins,
      losses: result.losses,
      draws: result.draws,
      games: result.games,
    };
    renderLeaderboard();
    renderRankResult(result, opponents);
    selection = [];
    renderDuel();
  } catch (err) {
    setStatus(`Ranking failed: ${err.message}`, true);
    console.error(err);
  } finally {
    button.disabled = false;
    progress.hidden = true;
  }
}

function renderRankResult(result, opponents) {
  const box = $('#rank-result');
  box.hidden = false;
  const rank = [...leaderboard].filter((e) => e.rating > result.rating).length + 1;
  box.innerHTML =
    `<div class="big">ELO ${Math.round(result.rating)}</div>` +
    `<p>Ranked against the top ${opponents.length} combatants ` +
    `(${GAMES_PER_OPPONENT} fights each, K=32, start 1500): ` +
    `${result.wins}W / ${result.losses}L / ${result.draws}D. ` +
    `That places you at <b>#${rank}</b> in the table. ` +
    `You are now selectable for a head-to-head below.</p>`;
  box.classList.remove('warn');
  box.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

// ---------------------------------------------------------------------------

$('#char-form').addEventListener('submit', rankCharacter);

initEngine().catch((err) => console.error(err));
