#!/usr/bin/env python3
# Copyright (c) 2026 Christian Mayer and the Mundus Mirabilis contributors.
# SPDX-License-Identifier: Apache-2.0

"""rpg_os-codegen: compile a ruleset JSON schema into a strongly typed C++ header.

Usage:
  python3 codegen/rpg_os_codegen.py --ruleset rulesets/dnd5e_srd.json  --out generated/
  python3 codegen/rpg_os_codegen.py --ruleset rulesets/tde5e_core.json --out generated/

Emits ``generated/<ruleset_id>_static.hpp``. The generated code is header-only,
depends only on rpg_os/common + rpg_os/core (never on the dynamic universal
engine), still reads the ruleset JSON at runtime for the *data* database
(archetypes, ...), and is clang-format clean.

Python 3, standard library only.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

BANNER = """// clang-format off
// Copyright (c) 2026 Christian Mayer and the Mundus Mirabilis contributors.
// SPDX-License-Identifier: Apache-2.0
//
// ============================================================================
// AUTOMATICALLY GENERATED BY RPG OS CODEGEN - DO NOT HAND EDIT
// The generated C++ code is Apache-2.0. The RULESET DATA embedded below is NOT
// covered by Apache-2.0: it is governed by the ruleset's own licence (stated
// in the ruleset JSON, linked below when known).
// Ruleset        : {ruleset_id} ({ruleset_name})
// Source         : {source}
// Licence        : {licence}
// Licence Source : {licence_source}
// Licence Notice : {licence_notice}
// Attribution    : {attribution}
// Comment        : {comment}
// ============================================================================
// clang-format on
"""

CXX_KEYWORDS = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "char8_t", "char16_t", "char32_t",
    "class", "compl", "concept", "const", "consteval", "constexpr", "constinit",
    "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum",
    "explicit", "export", "extern", "false", "float", "for", "friend", "goto",
    "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
    "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private",
    "protected", "public", "register", "reinterpret_cast", "requires", "return",
    "short", "signed", "sizeof", "static", "static_assert", "static_cast",
    "struct", "switch", "template", "this", "thread_local", "throw", "true",
    "try", "typedef", "typeid", "typename", "union", "unsigned", "using",
    "virtual", "void", "volatile", "wchar_t", "while", "xor", "xor_eq",
}


def words(text: str) -> list[str]:
    """Splits an identifier/name into alphanumeric words."""
    return [p for p in re.split(r"[^A-Za-z0-9]+", text) if p]


def camel_case(text: str) -> str:
    """Converts 'Base Attack', 'STR_mod' or 'dnd5e_attack_melee' to camelCase."""
    parts = words(text)
    if not parts:
        return "value"
    head = parts[0].lower()
    tail = "".join(p[:1].upper() + p[1:].lower() for p in parts[1:])
    name = head + tail
    if name in CXX_KEYWORDS:
        name += "_"
    return name


def pascal_case(text: str) -> str:
    """Converts 'Body Control' or 'climbing' to PascalCase ('BodyControl')."""
    parts = words(text)
    if not parts:
        return "Value"
    name = "".join(p[:1].upper() + p[1:].lower() for p in parts)
    if name in CXX_KEYWORDS:
        name += "_"
    return name


def check_method_name(ruleset_id: str, check_id: str) -> str:
    """The C++ method name for a check-type id, with the redundant ruleset
    prefix stripped.

    Every generated check method already lives inside the per-ruleset
    namespace (rpg_os::generated::<ruleset>), so carrying the ruleset prefix
    again in the method name ('dnd5e_attack_melee' -> 'dnd5eAttackMelee') is
    pure bloat. The prefix is the check id's first underscore-token when it is
    also a prefix of the ruleset id — 'dnd5e' < 'dnd5e_srd', 'tde' <
    'tde5e_core', 'brp' < 'brp_ugc' — so 'dnd5e_attack_melee' becomes
    'attackMelee' and 'tde_attack' becomes 'attack'. A check id without such a
    ruleset prefix is kept verbatim ('attack_melee' stays 'attackMelee').
    """
    first = check_id.split("_", 1)[0]
    if first and ruleset_id.startswith(first):
        rest = check_id[len(first):]
        if rest.startswith("_") and len(rest) > 1:
            return camel_case(rest[1:])
    return camel_case(check_id)


# Check-recipe enum strings -> rpg_os C++ enumerator names, shared by
# _recipe_init so every mapping lives in exactly one place.
_RECIPE_ENUMS = {
    "resolution": {
        "threshold": "Threshold", "pool": "Pool", "opposed": "Opposed",
        "resistance": "Resistance",
    },
    "comparison": {"ge": "GreaterEqual", "le": "LessEqual"},
    "threshold_source": {
        "difficulty": "Difficulty", "actor_stat": "ActorStat",
        "target_stat": "TargetStat",
    },
    "critical_style": {
        "none": "None", "face": "Face", "double": "DoubleRoll",
        "percentile": "PercentileBand",
    },
    "grading": {"none": "None", "percentile": "Percentile", "pool_quality": "PoolQuality"},
    "difficulty_mode": {"to_threshold": "ToThreshold", "to_stat": "ToStat"},
    "difficulty_multiplier": {"none": "None", "double_halve": "DoubleHalve"},
}


def _recipe_enum(field: str, value, default: str) -> str:
    """Maps a check-recipe JSON enum string to its rpg_os enumerator name.
    An absent value falls back to `default`; an *unknown* value is an
    authoring error and raises (never silently coerced)."""
    mapping = _RECIPE_ENUMS[field]
    if value is None:
        return default
    if value not in mapping:
        raise ValueError(f"unknown {field} '{value}' in check recipe")
    return mapping[value]


# Die sizes that have a dedicated user-defined literal suffix (_d2 ... _d100)
# in rpg_os::dice_literals. A ruleset JSON may use any die size, so anything
# outside this set falls back to the '"..."_dice' string literal form.
COMMON_DIE_SIZES = frozenset({2, 3, 4, 6, 8, 10, 12, 20, 30, 100})


def parse_dice_terms(expr: str):
    """Splits a dice expression like '2d6+4' or '1d6-1d6' into a list of
    (sign, kind, value, sides) terms, where kind is 'die' (value = count) or
    'const' (value = number, sides = None). Returns None when the string is
    not a well-formed dice expression (the caller then falls back to the
    string literal form). Mirrors the grammar of
    core/dice_engine.hpp's DiceExpression parser."""
    terms: list[tuple[int, str, int, int | None]] = []
    i = 0
    n = len(expr)
    while i < n:
        if expr[i] == " ":
            i += 1
            continue
        sign = 1
        if expr[i] == "+":
            i += 1
        elif expr[i] == "-":
            sign = -1
            i += 1
        start = i
        while i < n and expr[i].isdigit():
            i += 1
        has_number = i > start
        number = int(expr[start:i]) if has_number else None
        if i < n and expr[i] in "dD":
            i += 1
            s_start = i
            while i < n and expr[i].isdigit():
                i += 1
            if i == s_start:
                return None  # 'd' with no sides
            sides = int(expr[s_start:i])
            if sides <= 0:
                return None
            count = number if has_number else 1  # "d20" == "1d20"
            if count <= 0:
                return None
            terms.append((sign, "die", count, sides))
        else:
            if not has_number:
                return None  # unexpected character / trailing operator
            terms.append((sign, "const", number, None))
    return terms


def dice_literal(expr: str) -> str:
    """Renders a dice expression string as C++ that builds a DiceExpression
    from the readable die-size suffixes where possible — '1d20' becomes
    `1_d20`, '2d6+4' becomes `2_d6 + 4` — falling back to the '"..."_dice'
    string literal for unusual die sizes, malformed input, or
    constant-only expressions."""
    terms = parse_dice_terms(expr)
    if not terms or not any(kind == "die" for _, kind, _, _ in terms):
        return f'"{expr}"_dice'
    rendered: list[str] = []
    for i, (sign, kind, value, sides) in enumerate(terms):
        if kind == "die":
            if sides not in COMMON_DIE_SIZES:
                return f'"{expr}"_dice'
            token = f"{value}_d{sides}"
        else:
            token = str(value)
        if i == 0:
            rendered.append(("-" if sign < 0 else "") + token)
        else:
            rendered.append(("+ " if sign > 0 else "- ") + token)
    return " ".join(rendered)


class Expr:
    """A translated C++ subexpression with type and range information.

    kind is 'int' (exact integer arithmetic) or 'double' (floating point).
    frac is set only for an exact integer division `num / den`: the value is
    the *rational* num/den (emitted as a double division so later arithmetic
    stays exact), but a directly wrapping floor/ceil/round can replace it with
    the integer floorDiv/ceilDiv/roundDiv — keeping the generated hot path
    free of floating point wherever the ruleset formula allows it, and with
    the fast non-negative division helpers when the numerator is provably
    non-negative and the denominator a positive constant.

    non_neg records whether the value is provably >= 0 (ruleset stats are
    stored as unsigned bytes, sums/products of non-negatives stay
    non-negative), and const_val holds the integer value when the expression
    is an integer literal, so the code generator can pick the simplest C++.
    """

    __slots__ = ("code", "kind", "frac", "non_neg", "const_val")

    def __init__(self, code: str, kind: str, frac: "tuple[Expr, Expr] | None" = None,
                 non_neg: bool = False, const_val: int | None = None):
        self.code = code
        self.kind = kind
        self.frac = frac
        self.non_neg = non_neg
        self.const_val = const_val

    @staticmethod
    def int_(code: str, non_neg: bool = False, const_val: int | None = None) -> "Expr":
        return Expr(code, "int", non_neg=non_neg, const_val=const_val)

    @staticmethod
    def dbl(code: str, non_neg: bool = False) -> "Expr":
        return Expr(code, "double", non_neg=non_neg)

    def is_positive_constant(self) -> bool:
        """True when this is an integer literal greater than zero."""
        return self.const_val is not None and self.const_val > 0

    def as_double(self) -> str:
        return self.code if self.kind == "double" else f"static_cast<double>({self.code})"


class FormulaTranslator:
    """Translates the restricted formula grammar to a typed C++ expression.

    Identifiers are resolved via `resolve(identifier) -> C++ expression` and
    are assumed to be integer-typed (attributes / skills / derived getters).
    Integer arithmetic stays integer (no floating point in the generated hot
    path); a division of two integers is kept as an exact rational that a
    directly wrapping floor/ceil/round reduces with the integer division
    helpers. The result matches the universal double-based evaluator exactly
    (the parity tests pin this). `%` becomes std::fmod / `%`, `^` std::pow.
    """

    def __init__(self, resolve):
        self._resolve = resolve

    def translate(self, text: str) -> str:
        self._text = text
        self._pos = 0
        expr = self._parse_or()
        self._skip()
        if self._pos != len(self._text):
            raise ValueError(f"unexpected trailing characters in formula '{text}'")
        return expr.code

    # -- token helpers -----------------------------------------------------

    def _skip(self):
        while self._pos < len(self._text) and self._text[self._pos] in " \t\n":
            self._pos += 1

    def _consume(self, token: str) -> bool:
        if self._text.startswith(token, self._pos):
            self._pos += len(token)
            return True
        return False

    def _peek(self) -> str:
        return self._text[self._pos] if self._pos < len(self._text) else ""

    def _is_digit(self, c: str) -> bool:
        return c.isdigit()

    def _is_id_char(self, c: str) -> bool:
        return c.isalnum() or c in "_.'"

    # -- grammar (every node returns an Expr) ------------------------------

    def _parse_or(self) -> Expr:
        left = self._parse_and()
        while True:
            self._skip()
            if self._consume("||"):
                left = Expr.int_(f"({left.code} || {self._parse_and().code})")
            else:
                return left

    def _parse_and(self) -> Expr:
        left = self._parse_equality()
        while True:
            self._skip()
            if self._consume("&&"):
                left = Expr.int_(f"({left.code} && {self._parse_equality().code})")
            else:
                return left

    def _parse_equality(self) -> Expr:
        left = self._parse_relational()
        while True:
            self._skip()
            if self._consume("==") or self._consume("!="):
                op = "==" if self._text[self._pos - 2 : self._pos] == "==" else "!="
                right = self._parse_relational()
                left = Expr.int_(f"({self._bin_operand(left)} {op} {self._bin_operand(right)})")
            else:
                return left

    def _parse_relational(self) -> Expr:
        left = self._parse_additive()
        while True:
            self._skip()
            for op in ("<=", ">=", "<", ">"):
                if self._consume(op):
                    right = self._parse_additive()
                    left = Expr.int_(f"({self._bin_operand(left)} {op} {self._bin_operand(right)})")
                    break
            else:
                return left

    def _bin_operand(self, expr: Expr) -> str:
        """Operand for a comparison: integers compare directly, doubles promote."""
        return expr.code if expr.kind == "int" else expr.as_double()

    def _parse_additive(self) -> Expr:
        left = self._parse_multiplicative()
        while True:
            self._skip()
            for op in ("+", "-"):
                if self._consume(op):
                    right = self._parse_multiplicative()
                    if left.kind == "int" and right.kind == "int":
                        # A sum is non-negative if both sides are; a difference
                        # is only provably non-negative when subtracting zero.
                        non_neg = (left.non_neg and right.non_neg) if op == "+" else (
                            left.non_neg and right.const_val == 0)
                        left = Expr.int_(f"({left.code} {op} {right.code})", non_neg=non_neg)
                    else:
                        left = Expr.dbl(
                            f"({left.as_double()} {op} {right.as_double()})",
                            non_neg=left.non_neg and right.non_neg)
                    break
            else:
                return left

    def _parse_multiplicative(self) -> Expr:
        left = self._parse_unary()
        while True:
            self._skip()
            for op in ("*", "/", "%"):
                if self._consume(op):
                    right = self._parse_unary()
                    if op == "*":
                        if left.kind == "int" and right.kind == "int":
                            left = Expr.int_(f"({left.code} * {right.code})",
                                             non_neg=left.non_neg and right.non_neg)
                        else:
                            left = Expr.dbl(f"({left.as_double()} * {right.as_double()})",
                                            non_neg=left.non_neg and right.non_neg)
                    elif op == "/":
                        if left.kind == "int" and right.kind == "int":
                            # An exact rational: emit the double division (so
                            # later arithmetic stays exact) and remember the
                            # integer operands for a directly wrapping
                            # floor/ceil/round, which can then pick the fast
                            # non-negative helper when the numerator is proven
                            # non-negative and the denominator is a positive
                            # constant.
                            left = Expr(
                                f"static_cast<double>({left.code}) / static_cast<double>({right.code})",
                                "double",
                                frac=(left, right),
                                non_neg=left.non_neg and right.is_positive_constant(),
                            )
                        else:
                            left = Expr.dbl(f"({left.as_double()} / {right.as_double()})",
                                            non_neg=left.non_neg and right.non_neg)
                    else:  # '%'
                        if left.kind == "int" and right.kind == "int":
                            left = Expr.int_(f"({left.code} % {right.code})",
                                             non_neg=left.non_neg and right.non_neg)
                        else:
                            left = Expr.dbl(f"std::fmod({left.as_double()}, {right.as_double()})")
                    break
            else:
                return left

    def _parse_unary(self) -> Expr:
        self._skip()
        if self._consume("!"):
            return Expr.int_(f"(!{self._parse_unary().code})", non_neg=True)  # 0 or 1
        if self._consume("-"):
            inner = self._parse_unary()
            if inner.kind == "int":
                # Negation is non-negative only for the literal zero.
                return Expr.int_(f"(-{inner.code})", non_neg=inner.const_val == 0)
            return Expr.dbl(f"(-{inner.as_double()})", non_neg=inner.const_val == 0)
        return self._parse_power()

    def _parse_power(self) -> Expr:
        left = self._parse_primary()
        self._skip()
        if self._consume("^"):
            right = self._parse_unary()
            return Expr.dbl(f"std::pow({left.as_double()}, {right.as_double()})")
        return left

    def _parse_primary(self) -> Expr:
        self._skip()
        if self._pos >= len(self._text):
            raise ValueError(f"unexpected end of formula '{self._text}'")
        c = self._peek()
        if c == "(":
            self._pos += 1
            expr = self._parse_or()
            self._skip()
            if not self._consume(")"):
                raise ValueError(f"missing ')' in formula '{self._text}'")
            return expr
        if c.isdigit() or c == ".":
            return self._parse_number()
        if c.isalpha() or c == "_":
            ident = self._parse_identifier()
            self._skip()
            if self._consume("("):
                args = []
                self._skip()
                if not self._consume(")"):
                    while True:
                        args.append(self._parse_or())
                        self._skip()
                        if self._consume(")"):
                            break
                        if not self._consume(","):
                            raise ValueError(f"expected ',' or ')' in '{self._text}'")
                        self._skip()
                return self._call(ident, args)
            # A bare identifier is an integer stat reference; `resolve` also
            # reports whether the referenced storage is unsigned (=> non-neg).
            code, non_neg = self._resolve(ident)
            return Expr.int_(code, non_neg=non_neg)
        raise ValueError(f"unexpected character '{c}' in formula '{self._text}'")

    def _parse_number(self) -> Expr:
        start = self._pos
        while self._pos < len(self._text) and self._is_digit(self._text[self._pos]):
            self._pos += 1
        if self._pos < len(self._text) and self._text[self._pos] == ".":
            self._pos += 1
            while self._pos < len(self._text) and self._is_digit(self._text[self._pos]):
                self._pos += 1
        if self._pos == start:
            raise ValueError(f"expected a number in formula '{self._text}'")
        raw = self._text[start : self._pos]
        if "." in raw:
            return Expr.dbl(raw)
        value = int(raw)
        return Expr.int_(raw, non_neg=value >= 0, const_val=value)

    def _parse_identifier(self) -> str:
        start = self._pos
        while self._pos < len(self._text) and self._is_id_char(self._text[self._pos]):
            self._pos += 1
        return self._text[start : self._pos]

    def _call(self, name: str, args: list[Expr]) -> Expr:
        if name == "min":
            if len(args) != 2:
                raise ValueError(f"min() expects 2 arguments in '{self._text}'")
            non_neg = args[0].non_neg and args[1].non_neg
            if all(a.kind == "int" for a in args):
                return Expr.int_(f"rpg_os::math::minI({args[0].code}, {args[1].code})",
                                 non_neg=non_neg)
            return Expr.dbl(f"rpg_os::math::min({args[0].as_double()}, {args[1].as_double()})",
                            non_neg=non_neg)
        if name == "max":
            if len(args) != 2:
                raise ValueError(f"max() expects 2 arguments in '{self._text}'")
            non_neg = args[0].non_neg or args[1].non_neg
            if all(a.kind == "int" for a in args):
                return Expr.int_(f"rpg_os::math::maxI({args[0].code}, {args[1].code})",
                                 non_neg=non_neg)
            return Expr.dbl(f"rpg_os::math::max({args[0].as_double()}, {args[1].as_double()})",
                            non_neg=non_neg)
        if name in ("floor", "ceil", "round"):
            if len(args) != 1:
                raise ValueError(f"{name}() expects 1 argument in '{self._text}'")
            arg = args[0]
            if arg.frac is not None:
                num, den = arg.frac
                if num.non_neg and den.is_positive_constant():
                    # Ruleset stats never go negative here: use the single
                    # division fast path (floorDivN/ceilDivN/roundDivN).
                    helper = {"floor": "floorDivN", "ceil": "ceilDivN",
                              "round": "roundDivN"}[name]
                else:
                    helper = {"floor": "floorDiv", "ceil": "ceilDiv",
                              "round": "roundDiv"}[name]
                return Expr.int_(f"rpg_os::math::{helper}({num.code}, {den.code})",
                                 non_neg=True)
            if arg.kind == "int":
                return arg  # floor/ceil/round of an integer is itself
            fn = {"floor": "floor", "ceil": "ceil", "round": "round"}[name]
            return Expr.dbl(f"rpg_os::math::{fn}({arg.as_double()})",
                            non_neg=arg.non_neg)
        if name == "clamp":
            if len(args) != 3:
                raise ValueError(f"clamp() expects 3 arguments in '{self._text}'")
            if all(a.kind == "int" for a in args):
                # A clamp to a non-negative lower bound is non-negative.
                non_neg = args[1].non_neg or args[1].is_positive_constant()
                return Expr.int_(
                    f"rpg_os::math::clampInt({args[0].code}, {args[1].code}, {args[2].code})",
                    non_neg=non_neg)
            return Expr.dbl(
                f"rpg_os::math::clamp({args[0].as_double()}, {args[1].as_double()}, {args[2].as_double()})")
        raise ValueError(f"unknown function '{name}' in formula '{self._text}'")


class Generator:
    def __init__(self, ruleset: dict):
        self.rs = ruleset
        self.attrs = ruleset.get("attributes", [])
        self.derived = ruleset.get("derived_stats", [])
        self.resources = ruleset.get("resource_pools", [])
        self.skills = ruleset.get("skills", [])
        self.checks = ruleset.get("check_types", {})
        self.cost_tables = ruleset.get("cost_tables", {})
        # Optional coinage; None means the ruleset has no money and the
        # generated character simply has no typed money helpers.
        self.currency = ruleset.get("currencies")

        self.attr_members: dict[str, str] = {}
        for a in self.attrs:
            self.attr_members[a["id"]] = camel_case(a.get("name", a["id"]))
        self.derived_methods: dict[str, str] = {}
        for d in self.derived:
            self.derived_methods[d["id"]] = camel_case(d.get("name", d["id"]))
        self.skill_members: dict[str, str] = {}
        for s in self.skills:
            self.skill_members[s["id"]] = camel_case(s.get("name", s["id"]))

        # Stat ids the ruleset declares "wide" (int32_t): stats that can grow
        # beyond a byte even when their base bounds fit one (level, hit-point
        # maxima, armor rating, proficiency bonus) or back derived pools.
        # Declared per attribute in the ruleset JSON, never hard-coded here.
        self.wide_attr_ids = {a["id"] for a in self.attrs if a.get("wide")}

        # id -> storage type for every emitted member (attributes + skills).
        # The narrowest type that covers the ruleset-declared bounds is chosen
        # (attributes/skills in the shipped rulesets fit a uint8_t); the wide
        # ids above and all resource pools stay int32_t.
        self.attr_types: dict[str, str] = {}
        for a in self.attrs:
            self.attr_types[a["id"]] = (
                "int32_t" if a["id"] in self.wide_attr_ids
                else self._narrow_type(a.get("min", 0), a.get("max", 255)))
        self.skill_types: dict[str, str] = {
            s["id"]: self._narrow_type(s.get("min", 0), s.get("max", 255)) for s in self.skills
        }

        # id -> (C++ expression, non_neg) for use inside formulas. Attributes,
        # skills and derived getters are integer-typed; the translator keeps
        # integer arithmetic (no floating point in the generated hot path) and
        # only promotes to double where the formula itself needs an exact
        # division. non_neg is true for unsigned byte storage, which lets the
        # translator pick the single-division fast path for floor/ceil/round.
        def resolve(ident: str) -> tuple[str, bool]:
            if ident in self.attr_members:
                return f"static_cast<int>({self.attr_members[ident]})", \
                    self.attr_types[ident].startswith("u")
            if ident in self.derived_methods:
                return f"static_cast<int>({self.derived_methods[ident]}())", False
            if ident in self.skill_members:
                return f"static_cast<int>({self.skill_members[ident]})", \
                    self.skill_types[ident].startswith("u")
            raise ValueError(f"unknown stat '{ident}' referenced by a formula")

        self.translator = FormulaTranslator(resolve)

    @staticmethod
    def _narrow_type(min_value, max_value) -> str:
        """Smallest integral storage type covering [min_value, max_value]."""
        lo = int(min_value if min_value is not None else 0)
        hi = int(max_value if max_value is not None else 255)
        if lo >= 0 and hi <= 255:
            return "uint8_t"
        if lo >= -128 and hi <= 127:
            return "int8_t"
        if lo >= 0 and hi <= 65535:
            return "uint16_t"
        if lo >= -32768 and hi <= 32767:
            return "int16_t"
        return "int32_t"

    # -- members -----------------------------------------------------------

    def _resource_max_expr(self, max_stat: str) -> str:
        if max_stat in self.attr_members:
            return self.attr_members[max_stat]
        if max_stat in self.derived_methods:
            return f"{self.derived_methods[max_stat]}()"
        if max_stat in self.skill_members:
            return self.skill_members[max_stat]
        raise ValueError(f"resource max_stat '{max_stat}' is not a known stat")

    # -- generation --------------------------------------------------------

    def generate(self) -> str:
        lines: list[str] = []
        comment = self.rs.get("comment", "")
        lines.append(BANNER.format(ruleset_id=self.rs.get("ruleset_id", "ruleset"),
                                   ruleset_name=self.rs.get("ruleset_name", ""),
                                   source=self.rs.get("source", ""),
                                   licence=self.rs.get("licence", ""),
                                   licence_source=self.rs.get("licence_source", "") or "-",
                                   licence_notice=self.rs.get("licence_notice", "") or "-",
                                   attribution=self.rs.get("attribution", "") or "-",
                                   comment=comment if comment else "-"))
        # Doxygen file block so the generated header shows up under the
        # "Specific mode" module in the API reference (the module itself is
        # defined in docs/guides/user-guide.md).
        lines.append("/**")
        lines.append(f" * @file {self.rs.get('ruleset_id', 'ruleset')}_static.hpp")
        lines.append(" * @ingroup rpg_os_specific")
        lines.append(f" * @brief Strongly typed {self.rs.get('ruleset_name', 'character')} class,")
        lines.append(" * generated from the ruleset schema by the RPG OS code generator.")
        lines.append(" */")
        lines.append("#pragma once\n")
        lines.append("#include <array>")
        lines.append("#include <cstdint>")
        lines.append("#include <string>")
        lines.append("#include <string_view>")
        lines.append("#include <unordered_map>")
        lines.append("#include <unordered_set>")
        lines.append("#include <utility>")
        lines.append("#include <vector>")
        lines.append("")
        lines.append("#include <rpg_os/common/json.hpp>")
        lines.append("#include <rpg_os/common/types.hpp>")
        lines.append("#include <rpg_os/core/advancement.hpp>")
        lines.append("#include <rpg_os/core/checks.hpp>")
        lines.append("#include <rpg_os/core/cost_table.hpp>")
        lines.append("#include <rpg_os/core/dice_engine.hpp>")
        lines.append("#include <rpg_os/core/effects.hpp>")
        lines.append("#include <rpg_os/core/equipment.hpp>")
        lines.append("#include <rpg_os/core/inventory.hpp>")
        lines.append("#include <rpg_os/core/math.hpp>")
        lines.append("#include <rpg_os/core/money.hpp>")
        lines.append("#include <rpg_os/core/spellbook.hpp>")
        lines.append("#include <rpg_os/core/variance.hpp>")
        lines.append("#include <rpg_os/specific/sheet.hpp>")
        lines.append("#include <initializer_list>")
        lines.append("")

        for ns in self._namespace_parts():
            lines.append(f"namespace {ns} {{")
        lines.append("")
        lines.extend(self._class_doc())
        lines.append("class Character : public rpg_os::specific::SheetBase<Character> {")
        lines.append("public:")
        lines.extend(self._constructor())
        lines.append("")
        lines.extend(self._attribute_members())
        lines.extend(self._skill_members_block())
        lines.extend(self._resource_members())
        lines.extend(self._bookkeeping_members())
        lines.extend(self._runtime_state_members())
        lines.extend(self._to_json())
        lines.extend(self._restore_from_json())
        lines.extend(self._derived_getters())
        lines.extend(self._get_stat())
        lines.extend(self._check_methods())
        lines.extend(self._per_skill_checks())
        lines.extend(self._cost_table_accessors())
        lines.extend(self._data_loaders())
        lines.append("};")
        lines.append("")
        for ns in reversed(self._namespace_parts()):
            lines.append(f"}} // namespace {ns}")
        return "\n".join(lines) + "\n"

    def _namespace_parts(self) -> list[str]:
        ns = self.rs.get("namespace", f"rpg_os::generated::{self.rs.get('ruleset_id', 'x')}")
        return [p for p in ns.split("::") if p]

    def _class_doc(self) -> list[str]:
        name = self.rs.get("ruleset_name", "")
        return [f"/// Strongly typed character for the {name} ruleset. Attributes",
                "/// and skills are named members; derived stats are named getters with",
                "/// compiled formulas; checks are named methods over the shared",
                "/// templates. The data database is still read from the ruleset JSON."]

    def _constructor(self) -> list[str]:
        inits = [
            f"{self._member(r['id'], r.get('name'))}({self._resource_max_expr(r['max_stat'])})"
            for r in self.resources
        ]
        if not inits:
            return ["  /// Default-constructs a character with base values."]
        return ["  /// Default-constructs a character; resources start at their maximum.",
                "  Character() : " + ", ".join(inits) + " {}"]

    def _member(self, sid: str, name: str | None) -> str:
        return camel_case(name if name else sid)

    def _attribute_members(self) -> list[str]:
        lines = ["  // ---- core attributes (narrow storage where the ruleset allows) ----"]
        for a in self.attrs:
            if a["id"] in self.wide_attr_ids:
                continue
            member = self.attr_members[a["id"]]
            cpp_type = self.attr_types[a["id"]]
            lines.append(f"  {cpp_type} {member}{{ {a.get('default', 10)} }};  // {a['id']} {a.get('name', '')}")
        extras = [a for a in self.attrs if a["id"] in self.wide_attr_ids]
        if extras:
            lines.append("")
            lines.append("  // ---- other base stats (kept wide) ----")
            for a in extras:
                member = self.attr_members[a["id"]]
                lines.append(f"  int32_t {member}{{ {a.get('default', 0)} }};  // {a['id']} {a.get('name', '')}")
        return lines

    def _skill_members_block(self) -> list[str]:
        if not self.skills:
            return []
        lines = ["", "  // ---- skill ratings (narrow storage where the ruleset allows) ----"]
        for s in self.skills:
            cpp_type = self.skill_types[s["id"]]
            lines.append(f"  {cpp_type} {self.skill_members[s['id']]}{{ {s.get('default', 0)} }};  // {s['id']} ({s.get('name', '')})")
        return lines

    def _resource_members(self) -> list[str]:
        lines = ["", "  // ---- resources ----"]
        for r in self.resources:
            lines.append(f"  int32_t {self._member(r['id'], r.get('name'))}{{ 0 }};  // {r['id']} (max: {r['max_stat']})")
        return lines

    def _bookkeeping_members(self) -> list[str]:
        """Sheet bookkeeping state: inventory, worn gear, spellbook and
        advancement are always present (a generated character is a full
        sheet). Money and its typed helpers are emitted only when the ruleset
        declares a `currencies` section — a ruleset without money simply has
        no money members (the user-facing opt-in model)."""
        lines = ["", "  // ---- bookkeeping (inventory, gear, wealth, spells, advancement) ----",
                 "  rpg_os::Inventory inventory;",
                 "  rpg_os::Equipment equipment;",
                 "  rpg_os::Spellbook spellbook;",
                 "  rpg_os::Advancement advancement;"]
        if not self.currency:
            return lines
        lines.append("  rpg_os::Money money{0};  // wealth in base units")
        lines.append("")
        lines.append("  /// The ruleset's currency system (denominations + exchange).")
        lines.append("  static const rpg_os::CurrencySystem& currencySystem() {")
        lines.append("    static const rpg_os::CurrencySystem system = rpg_os::CurrencySystem{")
        lines.append(f'      "{self.currency.get("id", "coins")}",')
        lines.append(f'      "{self.currency.get("name", self.currency.get("id", "coins"))}",')
        lines.append(f'      "{self.currency.get("base_unit", "")}",')
        lines.append("      {")
        for d in self.currency.get("denominations", []):
            lines.append(f'        rpg_os::Denomination{{"{d["id"]}", "{d.get("name", d["id"])}", "{d.get("symbol", d["id"])}", {d.get("per_base", 1)}}},')
        lines.append("      }")
        lines.append("    };")
        lines.append("    return system;")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Adds a bag of coins to the character's wealth, e.g.")
        lines.append("  /// `depositCoins({{{\"gp\", 2}, {\"sp\", 5}}})`.")
        lines.append("  void depositCoins(std::initializer_list<std::pair<std::string, int64_t>> coins) {")
        lines.append("    money += rpg_os::Money::fromCoins(currencySystem(), coins);")
        lines.append("  }")
        lines.append("")
        lines.append("  /// How many whole `denomId` coins the wealth equals (floor).")
        lines.append("  [[nodiscard]] int64_t coinAmount(std::string_view denomId) const {")
        lines.append("    return money.in(currencySystem(), denomId);")
        lines.append("  }")
        return lines

    def _runtime_state_members(self) -> list[str]:
        """Living-sheet runtime state (save/load), distinct from the static
        ruleset-record members above: active conditions with stack counts, the
        effect timeline (timed conditions, temporary stat bonuses, bonus dice,
        recurring effects), temp HP, resistances, afflictions, and traits."""
        return [
            "",
            "  // ---- living-sheet runtime state (save/load) ----",
            "  std::unordered_map<std::string, int32_t> conditions;  // condition id -> stacks",
            "  rpg_os::EffectTimeline effects;  // timed conditions + temporary modifiers",
            "  int32_t tempHitPoints{0};",
            "  std::unordered_set<std::string> resistances;",
            "  std::vector<rpg_os::AppliedAffliction> afflictions;",
            "  std::unordered_set<std::string> traits;",
            "  std::string terrain;  // current terrain / surrounding (\"\" = ruleset default)",
        ]

    def _to_json(self) -> list[str]:
        """Serializes the living sheet's current state — attributes, skills,
        resource current values, conditions with durations, the effect
        timeline, temp HP, resistances, afflictions, traits, inventory,
        equipment, money, spell slots and advancement — in the same save-state
        shape as the universal @c rpg_os::DynamicEntity::toJson, so a save file
        is portable between the two modes."""
        lines = [
            "",
            "  // ---- save / load (snapshot the living sheet, not a ruleset record) ----",
            "  /// Serializes the character's current living state — attributes, skills,",
            "  /// resource current values, conditions with durations, the effect timeline,",
            "  /// temp HP, resistances, afflictions, traits, inventory, equipment, money,",
            "  /// spell slots, and advancement — in the same save-state shape as the",
            "  /// universal @c rpg_os::DynamicEntity::toJson.",
            "  void toJson(rpg_os::Json& out) const {",
            "    out = rpg_os::Json::object();",
        ]
        if self.attrs or self.skills:
            lines.append("    rpg_os::Json stats = rpg_os::Json::object();")
            for a in self.attrs:
                lines.append(f'    stats["{a["id"]}"] = static_cast<int32_t>({self.attr_members[a["id"]]});')
            for s in self.skills:
                lines.append(f'    stats["{s["id"]}"] = static_cast<int32_t>({self.skill_members[s["id"]]});')
            lines.append('    out["stats"] = stats;')
        if self.resources:
            lines.append("    rpg_os::Json resources = rpg_os::Json::object();")
            for r in self.resources:
                lines.append(f'    resources["{r["id"]}"] = {self._member(r["id"], r.get("name"))};')
            lines.append('    out["resources"] = resources;')
        lines += [
            '    out["terrain"] = terrain;',
            '    out["conditions"] = conditions;',
            "    rpg_os::Json traitsJson = rpg_os::Json::array();",
            "    for (const auto& traitId : traits) { traitsJson.push_back(traitId); }",
            '    out["traits"] = traitsJson;',
            "    rpg_os::Json inventoryJson;",
            "    inventory.toJson(inventoryJson);",
            '    out["inventory"] = inventoryJson;',
            "    rpg_os::Json equipmentJson;",
            "    equipment.toJson(equipmentJson);",
            '    out["equipment"] = equipmentJson;',
        ]
        if self.currency:
            lines.append('    out["money"] = money.baseUnits();')
        lines += [
            '    out["temp_hp"] = tempHitPoints;',
            "    rpg_os::Json spellbookJson;",
            "    spellbook.toJson(spellbookJson);",
            '    out["spellbook"] = spellbookJson;',
            "    rpg_os::Json advancementJson;",
            "    advancement.toJson(advancementJson);",
            '    out["advancement"] = advancementJson;',
            "    rpg_os::Json effectsJson;",
            "    effects.toJson(effectsJson);",
            '    out["effects"] = effectsJson;',
            "    rpg_os::Json afflictionsJson = rpg_os::Json::array();",
            "    for (const auto& affliction : afflictions) {",
            "      rpg_os::Json entry;",
            "      entry[\"section\"] = affliction.section;",
            "      entry[\"id\"] = affliction.id;",
            "      entry[\"conditions\"] = affliction.conditions;",
            "      afflictionsJson.push_back(std::move(entry));",
            "    }",
            '    out["afflictions"] = afflictionsJson;',
            "    rpg_os::Json resistancesJson = rpg_os::Json::array();",
            "    for (const auto& type : resistances) { resistancesJson.push_back(type); }",
            '    out["resistances"] = resistancesJson;',
            "  }",
        ]
        return lines

    def _restore_from_json(self) -> list[str]:
        """Restores the living state written by @ref toJson. State absent from
        `in` is left unchanged. Distinct from @ref fromJson, which loads a
        *ruleset* archetype / creature record from scratch."""
        lines = [
            "",
            "  /// Restores the living state written by @ref toJson. State absent from `in` is",
            "  /// left unchanged. Distinct from @ref fromJson, which loads a *ruleset*",
            "  /// archetype / creature record from scratch.",
            "  void restoreFromJson(const rpg_os::Json& in) {",
            "    if (!in.is_object()) { return; }",
        ]
        if self.attrs or self.skills:
            lines.append("    if (in.contains(\"stats\") && in.at(\"stats\").is_object()) {")
            lines.append("      const rpg_os::Json& stats = in.at(\"stats\");")
            for a in self.attrs:
                cpp_type = self.attr_types[a["id"]]
                lines.append(f'      {self.attr_members[a["id"]]} = static_cast<{cpp_type}>(stats.value("{a["id"]}", static_cast<int32_t>({self.attr_members[a["id"]]})));')
            for s in self.skills:
                cpp_type = self.skill_types[s["id"]]
                lines.append(f'      {self.skill_members[s["id"]]} = static_cast<{cpp_type}>(stats.value("{s["id"]}", static_cast<int32_t>({self.skill_members[s["id"]]})));')
            lines.append("    }")
        if self.resources:
            lines.append("    if (in.contains(\"resources\") && in.at(\"resources\").is_object()) {")
            lines.append("      const rpg_os::Json& resources = in.at(\"resources\");")
            for r in self.resources:
                lines.append(f'      {self._member(r["id"], r.get("name"))} = resources.value("{r["id"]}", {self._member(r["id"], r.get("name"))});')
            lines.append("    }")
        lines += [
            "    if (in.contains(\"terrain\") && in.at(\"terrain\").is_string()) {",
            "      terrain = in.at(\"terrain\").get<std::string>();",
            "    }",
            "    if (in.contains(\"conditions\") && in.at(\"conditions\").is_object()) {",
            "      conditions = in.at(\"conditions\").get<std::unordered_map<std::string, int32_t>>();",
            "    }",
            "    if (in.contains(\"traits\") && in.at(\"traits\").is_array()) {",
            "      traits.clear();",
            "      for (const auto& traitId : in.at(\"traits\")) { traits.insert(traitId.get<std::string>()); }",
            "    }",
            "    if (in.contains(\"inventory\")) { inventory.fromJson(in.at(\"inventory\")); }",
            "    if (in.contains(\"equipment\")) { equipment.fromJson(in.at(\"equipment\")); }",
        ]
        if self.currency:
            lines.append("    if (in.contains(\"money\") && in.at(\"money\").is_number_integer()) {")
            lines.append("      money = rpg_os::Money{in.at(\"money\").get<int64_t>()};")
            lines.append("    }")
        lines += [
            "    if (in.contains(\"temp_hp\") && in.at(\"temp_hp\").is_number_integer()) {",
            "      tempHitPoints = in.at(\"temp_hp\").get<int32_t>();",
            "    }",
            "    if (in.contains(\"spellbook\")) { spellbook.fromJson(in.at(\"spellbook\")); }",
            "    if (in.contains(\"advancement\")) { advancement.fromJson(in.at(\"advancement\")); }",
            "    if (in.contains(\"effects\")) { effects.fromJson(in.at(\"effects\")); }",
            "    if (in.contains(\"afflictions\") && in.at(\"afflictions\").is_array()) {",
            "      afflictions.clear();",
            "      for (const auto& aff : in.at(\"afflictions\")) {",
            "        afflictions.push_back(rpg_os::AppliedAffliction{",
            "          aff.value(\"section\", \"\"), aff.value(\"id\", \"\"),",
            "          aff.value(\"conditions\", std::vector<std::string>{})});",
            "      }",
            "    }",
            "    if (in.contains(\"resistances\") && in.at(\"resistances\").is_array()) {",
            "      resistances.clear();",
            "      for (const auto& type : in.at(\"resistances\")) { resistances.insert(type.get<std::string>()); }",
            "    }",
            "  }",
        ]
        return lines

    def _derived_getters(self) -> list[str]:
        lines = ["", "  // ---- derived stats (compiled formulas) ----"]
        for d in self.derived:
            method = self.derived_methods[d["id"]]
            expr = self.translator.translate(d["formula"])
            lines.append(f"  [[nodiscard]] int32_t {method}() const noexcept {{")
            lines.append(f"    return static_cast<int32_t>({expr});")
            lines.append(f"  }}  // {d['id']}: {d['formula']}")
        return lines

    def _get_stat(self) -> list[str]:
        lines = ["", "  // ---- StatProvider (string -> member switch, no allocations) ----",
                 "  [[nodiscard]] int32_t getStat(std::string_view id) const noexcept {"]
        for a in self.attrs:
            lines.append(f"    if (id == \"{a['id']}\") return {self.attr_members[a['id']]};")
        for s in self.skills:
            lines.append(f"    if (id == \"{s['id']}\") return {self.skill_members[s['id']]};")
        for d in self.derived:
            lines.append(f"    if (id == \"{d['id']}\") return {self.derived_methods[d['id']]}();")
        lines.append("    return 0;")
        lines.append("  }")
        return lines

    def _recipe_init(self, cfg: dict) -> tuple[list[str], bool]:
        """Designated-initializer lines for a rpg_os::CheckRecipe from a check
        config, plus whether the check needs a target entity.

        Every check the code generator emits is expressed as a *generic*
        recipe (see core/checks.hpp) rather than a ruleset-specific algorithm;
        the generated method is the only place a ruleset's check names appear.
        """
        lines: list[str] = []
        resolution = cfg.get("resolution", "threshold")
        source = cfg.get("threshold_source")
        lines.append("    .resolution = rpg_os::Resolution::" +
                     _recipe_enum("resolution", cfg.get("resolution"), "Threshold") + ",")
        lines.append(f'    .dice = {dice_literal(cfg.get("dice", "1d20"))},')
        lines.append("    .comparison = rpg_os::Comparison::" +
                     _recipe_enum("comparison", cfg.get("comparison"), "GreaterEqual") + ",")
        lines.append("    .thresholdSource = rpg_os::ThresholdSource::" +
                     _recipe_enum("threshold_source", source, "Difficulty") + ",")
        if cfg.get("threshold_stat"):
            lines.append(f'    .thresholdStat = "{cfg["threshold_stat"]}",')
        if cfg.get("bonus_stats"):
            lines.append("    .bonusStats = {" + ", ".join(f'"{b}"' for b in cfg["bonus_stats"]) + "},")
        if cfg.get("pool_attributes"):
            attrs = cfg["pool_attributes"]
            lines.append("    .poolAttributes = {" + ", ".join(f'"{a}"' for a in attrs) + "},")
            lines.append(f"    .numPoolAttributes = {len(attrs)},")
        if cfg.get("pool_stat"):
            lines.append(f'    .poolStat = "{cfg["pool_stat"]}",')
        if cfg.get("attack_stat"):
            lines.append(f'    .attackStat = "{cfg["attack_stat"]}",')
        if cfg.get("parry_stat"):
            lines.append(f'    .parryStat = "{cfg["parry_stat"]}",')
        if cfg.get("compare_levels"):
            lines.append("    .compareLevels = true,")
        lines.append("    .criticalStyle = rpg_os::CriticalStyle::" +
                     _recipe_enum("critical_style", cfg.get("critical_style"), "None") + ",")
        if cfg.get("critical_face"):
            lines.append(f"    .criticalFace = {cfg['critical_face']},")
        if cfg.get("critical_confirm"):
            lines.append("    .criticalConfirm = true,")
        lines.append("    .fumbleStyle = rpg_os::CriticalStyle::" +
                     _recipe_enum("critical_style", cfg.get("fumble_style"), "None") + ",")
        if cfg.get("fumble_face"):
            lines.append(f"    .fumbleFace = {cfg['fumble_face']},")
        if cfg.get("fumble_confirm"):
            lines.append("    .fumbleConfirm = true,")
        lines.append("    .grading = rpg_os::Grading::" +
                     _recipe_enum("grading", cfg.get("grading"), "None") + ",")
        lines.append("    .difficultyMode = rpg_os::DifficultyMode::" +
                     _recipe_enum("difficulty_mode", cfg.get("difficulty_mode"), "ToThreshold") +
                     ",")
        lines.append("    .difficultyMultiplier = rpg_os::DifficultyMultiplier::" +
                     _recipe_enum("difficulty_multiplier", cfg.get("difficulty_multiplier"),
                                  "None") + ",")
        needs_target = resolution in ("opposed", "resistance") or (
            resolution == "threshold" and source == "target_stat")
        return lines, needs_target

    def _check_methods(self) -> list[str]:
        lines = ["", "  // ---- named checks (from check_types) ----"]
        ruleset_id = self.rs.get("ruleset_id", "")
        for cid, cfg in self.checks.items():
            # The methods already live in the per-ruleset namespace, so the
            # ruleset prefix in the check id is stripped (see check_method_name).
            method = check_method_name(ruleset_id, cid)
            init_lines, needs_target = self._recipe_init(cfg)
            lines.append(f"  /// Named check '{cid}' (see the ruleset's check_types).")
            if needs_target:
                lines.append("  template <rpg_os::StatProvider Target, rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const Target& target, "
                             "const rpg_os::CheckParams& params, Rng& rng) const {")
            else:
                lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const rpg_os::CheckParams& params, Rng& rng) const {{")
            lines.append("    static const rpg_os::CheckRecipe recipe{")
            lines.extend(init_lines)
            lines.append("    };")
            if needs_target:
                lines.append("    return rpg_os::resolveCheck(*this, target, recipe, params, rng);")
            else:
                lines.append("    return rpg_os::resolveCheck(*this, rpg_os::NullStatProvider{}, recipe, params, rng);")
            lines.append("  }")
            lines.append("")
        return lines

    def _per_skill_checks(self) -> list[str]:
        if not self.skills:
            return []
        lines = ["  // ---- per-skill checks (each skill's own linked attributes as a pool) ----"]
        for s in self.skills:
            attrs = s.get("attributes", [])
            if len(attrs) != 3:
                # A pool check rolls against exactly three linked attributes.
                continue
            method = "check" + pascal_case(s["name"] if s.get("name") else s["id"])
            recipe_cfg = {
                "resolution": "pool",
                "dice": "3d20",
                "pool_attributes": attrs,
                "pool_stat": s["id"],
                "critical_style": "double",
                "fumble_style": "double",
                "grading": "pool_quality",
                "difficulty_mode": "to_stat",
            }
            init_lines, _ = self._recipe_init(recipe_cfg)
            lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
            lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const rpg_os::CheckParams& params, Rng& rng) const {{")
            lines.append("    static const rpg_os::CheckRecipe recipe{")
            lines.extend(init_lines)
            lines.append("    };")
            lines.append("    return rpg_os::resolveCheck(*this, rpg_os::NullStatProvider{}, recipe, params, rng);")
            lines.append("  }")
        return lines

    def _cost_table_accessors(self) -> list[str]:
        lines = ["", "  // ---- cost / progression tables ----"]
        for tid, tbl in self.cost_tables.items():
            method = camel_case(tid)
            kind = "CostTable::Kind::Threshold" if tbl["type"] == "threshold" else "CostTable::Kind::Multiplier"
            entries = []
            if "thresholds" in tbl:
                for e in tbl["thresholds"]:
                    entries.append(f"{{ {e['key']}, {e['value']} }}")
            elif "values" in tbl:
                for k, v in tbl["values"].items():
                    entries.append(f"{{ {k}, {v} }}")
            body = ", ".join(entries)
            lines.append(f"  /// Cost table '{tid}'.")
            lines.append(f"  static const rpg_os::CostTable& {method}() {{")
            lines.append(f"    static const rpg_os::CostTable table = rpg_os::CostTable::fromEntries(")
            lines.append(f"        {kind}, {tbl.get('base_factor', 1.0)}, {{{body}}});")
            lines.append("    return table;")
            lines.append("  }")
        return lines

    def _data_loaders(self) -> list[str]:
        lines = ["", "  // ---- data loading (the ruleset JSON is still read at runtime) ----",
                 "  /// Populates this character from a ruleset data record (archetype);",
                 "  /// ranged values are picked at random.",
                 "  void fromJson(const rpg_os::Json& record) {",
                 "    rpg_os::DefaultRandom rng;",
                 "    fromJson(record, rpg_os::Variance::Random, rng);",
                 "  }",
                 "",
                 "  /// As above, but picks ranged values according to `variance` (weakest,",
                 "  /// weak, average, strong, strongest) with the caller-supplied RNG.",
                 "  template <rpg_os::RandomNumberGenerator Rng>",
                 "  void fromJson(const rpg_os::Json& record, rpg_os::Variance variance, Rng& rng) {"]
        if self.attrs:
            lines.append("    if (record.contains(\"attributes\")) {")
            lines.append("      for (const auto& [key, value] : record.at(\"attributes\").items()) {")
            for a in self.attrs:
                cpp_type = self.attr_types[a["id"]]
                lines.append(f"        if (key == \"{a['id']}\") {{ {self.attr_members[a['id']]} = static_cast<{cpp_type}>(rpg_os::readVariantValue(value, variance, rng)); }}")
            lines.append("      }")
            lines.append("    }")
        if self.skills:
            lines.append("    if (record.contains(\"skills\")) {")
            lines.append("      for (const auto& [key, value] : record.at(\"skills\").items()) {")
            for s in self.skills:
                cpp_type = self.skill_types[s["id"]]
                lines.append(f"        if (key == \"{s['id']}\") {{ {self.skill_members[s['id']]} = static_cast<{cpp_type}>(rpg_os::readVariantValue(value, variance, rng)); }}")
            lines.append("      }")
            lines.append("    }")
        # refresh resources to their maximum, then honour explicit overrides
        for r in self.resources:
            member = self._member(r["id"], r.get("name"))
            lines.append(f"    {member} = {self._resource_max_expr(r['max_stat'])};")
        if self.resources:
            lines.append("    if (record.contains(\"resources\")) {")
            lines.append("      for (const auto& [key, value] : record.at(\"resources\").items()) {")
            for r in self.resources:
                lines.append(f"        if (key == \"{r['id']}\") {{ {self._member(r['id'], r.get('name'))} = rpg_os::readVariantValue(value, variance, rng); }}")
            lines.append("      }")
            lines.append("    }")
        # Bookkeeping fields a record may declare: wealth, starting gear,
        # known spells, and experience. Each is optional; the flat
        # equipment/slot and flat-spellbook forms mirror the universal loader.
        if self.currency:
            lines.append("    if (record.contains(\"wealth\") && record.at(\"wealth\").is_object()) {")
            lines.append("      int64_t total = 0;")
            lines.append("      for (const auto& [denom, qty] : record.at(\"wealth\").items()) {")
            lines.append("        total += currencySystem().valueOf(denom, qty.get<int64_t>());")
            lines.append("      }")
            lines.append("      money = rpg_os::Money{total};")
            lines.append("    }")
        lines.append("    if (record.contains(\"equipment\") && record.at(\"equipment\").is_object()) {")
        lines.append("      for (const auto& [slot, item] : record.at(\"equipment\").items()) {")
        lines.append("        (void)equipment.equip(slot, item.get<std::string>());")
        lines.append("      }")
        lines.append("    }")
        lines.append("    if (record.contains(\"spells_known\") && record.at(\"spells_known\").is_array()) {")
        lines.append("      for (const auto& spellId : record.at(\"spells_known\")) {")
        lines.append("        spellbook.learn(spellId.get<std::string>());")
        lines.append("      }")
        lines.append("    }")
        lines.append("    if (record.contains(\"xp\")) {")
        lines.append("      advancement.gainXp(record.at(\"xp\").get<int64_t>());")
        lines.append("    }")
        lines.append("    if (record.contains(\"level\")) {")
        lines.append("      advancement.level = record.at(\"level\").get<int32_t>();")
        lines.append("    }")
        lines.append("  }")
        return lines


def generate(ruleset: dict) -> str:
    return Generator(ruleset).generate()


def main() -> int:
    parser = argparse.ArgumentParser(description="RPG OS code generator")
    parser.add_argument("--ruleset", required=True, help="path to the ruleset JSON")
    parser.add_argument("--out", required=True, help="output directory")
    args = parser.parse_args()

    try:
        ruleset_path = pathlib.Path(args.ruleset)
        ruleset = json.loads(ruleset_path.read_text(encoding="utf-8"))
        header = generate(ruleset)
        ruleset_id = ruleset["ruleset_id"]
        out_dir = pathlib.Path(args.out)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / f"{ruleset_id}_static.hpp"
        out_file.write_text(header, encoding="utf-8")
    except (OSError, json.JSONDecodeError, KeyError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {out_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
