var dir_59425e443f801f1f2fd8bbe4959a3ccf =
[
    [ "test_advancement.cpp", "test__advancement_8cpp.html", "test__advancement_8cpp" ],
    [ "test_check_resolver.cpp", "test__check__resolver_8cpp.html", "test__check__resolver_8cpp" ],
    [ "test_checks.cpp", "test__checks_8cpp.html", "test__checks_8cpp" ],
    [ "test_codegen_output.cpp", "test__codegen__output_8cpp.html", "test__codegen__output_8cpp" ],
    [ "test_combat.cpp", "test__combat_8cpp.html", "test__combat_8cpp" ],
    [ "test_combat_session.cpp", "test__combat__session_8cpp.html", "test__combat__session_8cpp" ],
    [ "test_conditions.cpp", "test__conditions_8cpp.html", "test__conditions_8cpp" ],
    [ "test_cost_table.cpp", "test__cost__table_8cpp.html", "test__cost__table_8cpp" ],
    [ "test_data_api.cpp", "test__data__api_8cpp.html", "test__data__api_8cpp" ],
    [ "test_dice.cpp", "test__dice_8cpp.html", "test__dice_8cpp" ],
    [ "test_effects.cpp", "test__effects_8cpp.html", "test__effects_8cpp" ],
    [ "test_engine.cpp", "test__engine_8cpp.html", "test__engine_8cpp" ],
    [ "test_entity.cpp", "test__entity_8cpp.html", "test__entity_8cpp" ],
    [ "test_entity_registry.cpp", "test__entity__registry_8cpp.html", "test__entity__registry_8cpp" ],
    [ "test_equipment.cpp", "test__equipment_8cpp.html", "test__equipment_8cpp" ],
    [ "test_errors.cpp", "test__errors_8cpp.html", "test__errors_8cpp" ],
    [ "test_event_system.cpp", "test__event__system_8cpp.html", "test__event__system_8cpp" ],
    [ "test_expression.cpp", "test__expression_8cpp.html", "test__expression_8cpp" ],
    [ "test_fixtures.hpp", "test__fixtures_8hpp.html", "test__fixtures_8hpp" ],
    [ "test_game_session.cpp", "test__game__session_8cpp.html", "test__game__session_8cpp" ],
    [ "test_inventory.cpp", "test__inventory_8cpp.html", "test__inventory_8cpp" ],
    [ "test_main.cpp", "test__main_8cpp.html", "test__main_8cpp" ],
    [ "test_math.cpp", "test__math_8cpp.html", "test__math_8cpp" ],
    [ "test_modifier.cpp", "test__modifier_8cpp.html", "test__modifier_8cpp" ],
    [ "test_money.cpp", "test__money_8cpp.html", "test__money_8cpp" ],
    [ "test_ruleset_loader.cpp", "test__ruleset__loader_8cpp.html", "test__ruleset__loader_8cpp" ],
    [ "test_rulesets.cpp", "test__rulesets_8cpp.html", "test__rulesets_8cpp" ],
    [ "test_smoke.cpp", "test__smoke_8cpp.html", "test__smoke_8cpp" ],
    [ "test_spellcasting.cpp", "test__spellcasting_8cpp.html", "test__spellcasting_8cpp" ],
    [ "test_traits.cpp", "test__traits_8cpp.html", "test__traits_8cpp" ],
    [ "test_types.cpp", "test__types_8cpp.html", "test__types_8cpp" ],
    [ "test_util.hpp", "test__util_8hpp.html", "test__util_8hpp" ],
    [ "test_variance.cpp", "test__variance_8cpp.html", "test__variance_8cpp" ],
    [ "test_world_state.cpp", "test__world__state_8cpp.html", "test__world__state_8cpp" ]
];