var hierarchy =
[
    [ "rpg_os::RulesetEngine::AfflictionResult", "structrpg__os_1_1RulesetEngine_1_1AfflictionResult.html", null ],
    [ "rpg_os::AttributeDef", "structrpg__os_1_1AttributeDef.html", null ],
    [ "rpg_os::generated::brp_ugc::Character", "classrpg__os_1_1generated_1_1brp__ugc_1_1Character.html", null ],
    [ "rpg_os::generated::dnd5e::Character", "classrpg__os_1_1generated_1_1dnd5e_1_1Character.html", null ],
    [ "rpg_os::generated::tde5e::Character", "classrpg__os_1_1generated_1_1tde5e_1_1Character.html", null ],
    [ "rpg_os::CheckParams", "structrpg__os_1_1CheckParams.html", null ],
    [ "rpg_os::CheckRecipe", "structrpg__os_1_1CheckRecipe.html", null ],
    [ "rpg_os::CheckResolver", "classrpg__os_1_1CheckResolver.html", null ],
    [ "rpg_os::CheckResult", "structrpg__os_1_1CheckResult.html", null ],
    [ "rpg_os::CheckTypeDef", "structrpg__os_1_1CheckTypeDef.html", null ],
    [ "rpg_os::CombatantSpec", "structrpg__os_1_1CombatantSpec.html", null ],
    [ "rpg_os::CostTable", "classrpg__os_1_1CostTable.html", null ],
    [ "rpg_os::CostTableDef", "structrpg__os_1_1CostTableDef.html", null ],
    [ "rpg_os::DefaultRandom", "classrpg__os_1_1DefaultRandom.html", null ],
    [ "rpg_os::DerivedStatDef", "structrpg__os_1_1DerivedStatDef.html", null ],
    [ "rpg_os::DiceExpression", "classrpg__os_1_1DiceExpression.html", null ],
    [ "rpg_os::DieSpec", "structrpg__os_1_1DieSpec.html", null ],
    [ "rpg_os::DynamicEntity", "classrpg__os_1_1DynamicEntity.html", null ],
    [ "rpg_os::CostTable::Entry", "structrpg__os_1_1CostTable_1_1Entry.html", null ],
    [ "rpg_os::EvalContext", "classrpg__os_1_1EvalContext.html", [
      [ "rpg_os::EntityContext", "classrpg__os_1_1EntityContext.html", null ]
    ] ],
    [ "rpg_os::EventActionDef", "structrpg__os_1_1EventActionDef.html", null ],
    [ "rpg_os::EventBus", "classrpg__os_1_1EventBus.html", null ],
    [ "rpg_os::EventData", "structrpg__os_1_1EventData.html", null ],
    [ "rpg_os::EventTriggerDef", "structrpg__os_1_1EventTriggerDef.html", null ],
    [ "rpg_os::Expression", "classrpg__os_1_1Expression.html", null ],
    [ "rpg_os::FightOutcome", "structrpg__os_1_1FightOutcome.html", null ],
    [ "MockStats", "structMockStats.html", null ],
    [ "rpg_os::Modifier", "structrpg__os_1_1Modifier.html", null ],
    [ "rpg_os::NullStatProvider", "structrpg__os_1_1NullStatProvider.html", null ],
    [ "rpg_os::ResourcePool", "structrpg__os_1_1ResourcePool.html", null ],
    [ "rpg_os::ResourcePoolDef", "structrpg__os_1_1ResourcePoolDef.html", null ],
    [ "rpg_os::Ruleset", "classrpg__os_1_1Ruleset.html", null ],
    [ "rpg_os::RulesetEngine", "classrpg__os_1_1RulesetEngine.html", null ],
    [ "rpg_os::RulesetLoader", "classrpg__os_1_1RulesetLoader.html", null ],
    [ "ScriptedRng", "structScriptedRng.html", null ],
    [ "rpg_os::SkillDef", "structrpg__os_1_1SkillDef.html", null ],
    [ "rpg_os::RulesetEngine::SpellResult", "structrpg__os_1_1RulesetEngine_1_1SpellResult.html", null ]
];